// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rule_b_reg_attributes_3_reload,
        rule_b_reg_attributes_2_reload,
        rule_b_reg_attributes_1_reload,
        rule_b_reg_attributes_reload,
        rule_b_reg_objects_3_reload,
        rule_b_reg_objects_2_reload,
        rule_b_reg_objects_1_reload,
        rule_b_reg_objects_reload,
        rule_b_reg_subjects_3_reload,
        rule_b_reg_subjects_2_reload,
        rule_b_reg_subjects_1_reload,
        rule_b_reg_subjects_reload,
        rule_a_reg_attributes_3_reload,
        rule_a_reg_attributes_2_reload,
        rule_a_reg_attributes_1_reload,
        rule_a_reg_attributes_reload,
        rule_a_reg_objects_3_reload,
        rule_a_reg_objects_2_reload,
        rule_a_reg_objects_1_reload,
        rule_a_reg_objects_reload,
        rule_a_reg_subjects_3_reload,
        rule_a_reg_subjects_2_reload,
        rule_a_reg_subjects_1_reload,
        rule_a_reg_subjects_reload,
        add_ln46,
        trunc_ln3,
        subj_mask,
        trunc_ln2,
        obj_mask,
        trunc_ln5,
        trunc_ln6,
        trunc_ln8,
        trunc_ln9,
        trunc_ln7,
        source_assign,
        trunc_ln4,
        policy_Addr_A,
        policy_EN_A,
        policy_WEN_A,
        policy_Din_A,
        policy_Dout_A,
        policy_Addr_B,
        policy_EN_B,
        policy_WEN_B,
        policy_Din_B,
        policy_Dout_B,
        bounded_rule_count,
        found_out,
        found_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] rule_b_reg_attributes_3_reload;
input  [63:0] rule_b_reg_attributes_2_reload;
input  [63:0] rule_b_reg_attributes_1_reload;
input  [63:0] rule_b_reg_attributes_reload;
input  [63:0] rule_b_reg_objects_3_reload;
input  [63:0] rule_b_reg_objects_2_reload;
input  [63:0] rule_b_reg_objects_1_reload;
input  [63:0] rule_b_reg_objects_reload;
input  [63:0] rule_b_reg_subjects_3_reload;
input  [63:0] rule_b_reg_subjects_2_reload;
input  [63:0] rule_b_reg_subjects_1_reload;
input  [63:0] rule_b_reg_subjects_reload;
input  [63:0] rule_a_reg_attributes_3_reload;
input  [63:0] rule_a_reg_attributes_2_reload;
input  [63:0] rule_a_reg_attributes_1_reload;
input  [63:0] rule_a_reg_attributes_reload;
input  [63:0] rule_a_reg_objects_3_reload;
input  [63:0] rule_a_reg_objects_2_reload;
input  [63:0] rule_a_reg_objects_1_reload;
input  [63:0] rule_a_reg_objects_reload;
input  [63:0] rule_a_reg_subjects_3_reload;
input  [63:0] rule_a_reg_subjects_2_reload;
input  [63:0] rule_a_reg_subjects_1_reload;
input  [63:0] rule_a_reg_subjects_reload;
input  [8:0] add_ln46;
input  [1:0] trunc_ln3;
input  [63:0] subj_mask;
input  [1:0] trunc_ln2;
input  [63:0] obj_mask;
input  [63:0] trunc_ln5;
input  [63:0] trunc_ln6;
input  [63:0] trunc_ln8;
input  [63:0] trunc_ln9;
input  [31:0] trunc_ln7;
input  [31:0] source_assign;
input  [8:0] trunc_ln4;
output  [31:0] policy_Addr_A;
output   policy_EN_A;
output  [127:0] policy_WEN_A;
output  [1023:0] policy_Din_A;
input  [1023:0] policy_Dout_A;
output  [31:0] policy_Addr_B;
output   policy_EN_B;
output  [127:0] policy_WEN_B;
output  [1023:0] policy_Din_B;
input  [1023:0] policy_Dout_B;
input  [9:0] bounded_rule_count;
output  [0:0] found_out;
output   found_out_ap_vld;

reg ap_idle;
reg found_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln46_fu_751_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] found_reg_578;
reg   [0:0] stage1_valid_reg_591;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln46_reg_2416;
reg   [0:0] icmp_ln46_reg_2416_pp0_iter1_reg;
wire   [0:0] stage1_valid_1_fu_763_p2;
reg   [0:0] stage1_valid_1_reg_2420;
reg   [0:0] stage1_valid_1_reg_2420_pp0_iter1_reg;
wire   [0:0] icmp_ln59_fu_788_p2;
reg   [0:0] icmp_ln59_reg_2446;
wire   [0:0] state_ok_fu_1025_p2;
reg   [0:0] state_ok_reg_2456;
wire   [0:0] icmp_ln95_fu_1031_p2;
reg   [0:0] icmp_ln95_reg_2461;
wire   [0:0] icmp_ln98_fu_1042_p2;
reg   [0:0] icmp_ln98_reg_2466;
wire   [0:0] xor_ln37_fu_1060_p2;
reg   [0:0] xor_ln37_reg_2471;
wire   [0:0] state_ok_1_fu_1203_p2;
reg   [0:0] state_ok_1_reg_2476;
wire   [0:0] icmp_ln95_1_fu_1209_p2;
reg   [0:0] icmp_ln95_1_reg_2481;
wire   [0:0] icmp_ln98_1_fu_1220_p2;
reg   [0:0] icmp_ln98_1_reg_2486;
wire   [0:0] xor_ln37_1_fu_1238_p2;
reg   [0:0] xor_ln37_1_reg_2491;
wire   [0:0] found_1_fu_2125_p9;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln58_fu_775_p1;
wire   [63:0] zext_ln60_fu_794_p1;
reg   [8:0] p_fu_208;
wire   [8:0] add_ln46_1_fu_757_p2;
reg   [8:0] ap_sig_allocacmp_p_1;
reg   [31:0] rule_a_reg_required_states_val6_fu_212;
wire   [31:0] rule_a_reg_required_states_val5_fu_1900_p3;
reg   [31:0] required_assign_fu_216;
wire   [31:0] rule_a_reg_required_provenance_val7_fu_1893_p3;
reg   [31:0] rule_b_reg_required_states_val10_fu_220;
wire   [31:0] rule_b_reg_required_states_val9_fu_1873_p9;
reg   [31:0] required_assign_1_fu_224;
wire   [31:0] rule_b_reg_required_provenance_val_fu_1853_p9;
reg   [63:0] rule_a_reg_subjects_fu_228;
wire   [63:0] rule_a_reg_subjects_11_fu_1846_p3;
reg   [63:0] rule_a_reg_subjects_1_fu_232;
wire   [63:0] rule_a_reg_subjects_10_fu_1839_p3;
reg   [63:0] rule_a_reg_subjects_2_fu_236;
wire   [63:0] rule_a_reg_subjects_9_fu_1832_p3;
reg   [63:0] rule_a_reg_subjects_3_fu_240;
wire   [63:0] rule_a_reg_subjects_8_fu_1825_p3;
reg   [63:0] rule_a_reg_objects_fu_244;
wire   [63:0] rule_a_reg_objects_11_fu_1818_p3;
reg   [63:0] rule_a_reg_objects_1_fu_248;
wire   [63:0] rule_a_reg_objects_10_fu_1811_p3;
reg   [63:0] rule_a_reg_objects_2_fu_252;
wire   [63:0] rule_a_reg_objects_9_fu_1804_p3;
reg   [63:0] rule_a_reg_objects_3_fu_256;
wire   [63:0] rule_a_reg_objects_8_fu_1797_p3;
reg   [63:0] rule_a_reg_attributes_fu_260;
wire   [63:0] rule_a_reg_attributes_11_fu_1790_p3;
reg   [63:0] rule_a_reg_attributes_1_fu_264;
wire   [63:0] rule_a_reg_attributes_10_fu_1783_p3;
reg   [63:0] rule_a_reg_attributes_2_fu_268;
wire   [63:0] rule_a_reg_attributes_9_fu_1776_p3;
reg   [63:0] rule_a_reg_attributes_3_fu_272;
wire   [63:0] rule_a_reg_attributes_8_fu_1769_p3;
reg   [63:0] rule_b_reg_subjects_fu_276;
wire   [63:0] rule_b_reg_subjects_6_fu_1749_p9;
reg   [63:0] rule_b_reg_subjects_1_fu_280;
wire   [63:0] rule_b_reg_subjects_5_fu_1729_p9;
reg   [63:0] rule_b_reg_subjects_2_fu_284;
wire   [63:0] rule_b_reg_subjects_4_fu_1709_p9;
reg   [63:0] rule_b_reg_subjects_3_fu_288;
wire   [63:0] rule_b_reg_subjects_7_fu_1689_p9;
reg   [63:0] rule_b_reg_objects_fu_292;
wire   [63:0] rule_b_reg_objects_6_fu_1669_p9;
reg   [63:0] rule_b_reg_objects_1_fu_296;
wire   [63:0] rule_b_reg_objects_5_fu_1649_p9;
reg   [63:0] rule_b_reg_objects_2_fu_300;
wire   [63:0] rule_b_reg_objects_4_fu_1629_p9;
reg   [63:0] rule_b_reg_objects_3_fu_304;
wire   [63:0] rule_b_reg_objects_7_fu_1609_p9;
reg   [63:0] rule_b_reg_attributes_fu_308;
wire   [63:0] rule_b_reg_attributes_6_fu_1589_p9;
reg   [63:0] rule_b_reg_attributes_1_fu_312;
wire   [63:0] rule_b_reg_attributes_5_fu_1569_p9;
reg   [63:0] rule_b_reg_attributes_2_fu_316;
wire   [63:0] rule_b_reg_attributes_4_fu_1549_p9;
reg   [63:0] rule_b_reg_attributes_3_fu_320;
wire   [63:0] rule_b_reg_attributes_7_fu_1529_p9;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage0_01001;
reg    policy_EN_B_local;
wire   [31:0] policy_Addr_B_local;
wire   [31:0] policy_Addr_B_orig;
reg    policy_EN_A_local;
wire   [31:0] policy_Addr_A_local;
wire   [31:0] policy_Addr_A_orig;
wire   [8:0] shl_ln57_fu_769_p2;
wire   [9:0] or_ln_fu_780_p3;
wire   [63:0] tmp_fu_888_p9;
wire   [63:0] tmp_fu_888_p11;
wire   [63:0] and_ln28_fu_911_p2;
wire   [63:0] tmp_1_fu_922_p9;
wire   [63:0] tmp_1_fu_922_p11;
wire   [63:0] and_ln29_fu_945_p2;
wire   [63:0] and_ln31_fu_956_p2;
wire   [63:0] and_ln32_fu_966_p2;
wire   [63:0] and_ln33_fu_976_p2;
wire   [0:0] icmp_ln32_fu_971_p2;
wire   [0:0] icmp_ln33_fu_981_p2;
wire   [0:0] and_ln31_1_fu_986_p2;
wire   [0:0] icmp_ln31_fu_961_p2;
wire   [63:0] and_ln34_fu_998_p2;
wire   [0:0] and_ln31_2_fu_992_p2;
wire   [0:0] icmp_ln34_fu_1003_p2;
wire   [0:0] not_and_ln31_2_fu_1008_p2;
wire   [31:0] and_ln35_fu_1020_p2;
wire   [31:0] and_ln98_fu_1037_p2;
wire   [0:0] obj_ok_fu_950_p2;
wire   [0:0] empty_fu_1014_p2;
wire   [0:0] or_ln51_2_fu_1048_p2;
wire   [0:0] subj_ok_fu_916_p2;
wire   [0:0] or_ln51_fu_1054_p2;
wire   [63:0] tmp_2_fu_1066_p9;
wire   [63:0] tmp_2_fu_1066_p11;
wire   [63:0] and_ln28_1_fu_1089_p2;
wire   [63:0] tmp_3_fu_1100_p9;
wire   [63:0] tmp_3_fu_1100_p11;
wire   [63:0] and_ln29_1_fu_1123_p2;
wire   [63:0] and_ln31_3_fu_1134_p2;
wire   [63:0] and_ln32_1_fu_1144_p2;
wire   [63:0] and_ln33_1_fu_1154_p2;
wire   [0:0] icmp_ln32_1_fu_1149_p2;
wire   [0:0] icmp_ln33_1_fu_1159_p2;
wire   [0:0] and_ln31_4_fu_1164_p2;
wire   [0:0] icmp_ln31_1_fu_1139_p2;
wire   [63:0] and_ln34_1_fu_1176_p2;
wire   [0:0] and_ln31_5_fu_1170_p2;
wire   [0:0] icmp_ln34_1_fu_1181_p2;
wire   [0:0] not_and_ln31_5_fu_1186_p2;
wire   [31:0] and_ln35_1_fu_1198_p2;
wire   [31:0] and_ln98_1_fu_1215_p2;
wire   [0:0] obj_ok_1_fu_1128_p2;
wire   [0:0] empty_18_fu_1192_p2;
wire   [0:0] or_ln51_3_fu_1226_p2;
wire   [0:0] subj_ok_1_fu_1094_p2;
wire   [0:0] or_ln51_1_fu_1232_p2;
wire   [0:0] and_ln59_fu_1512_p2;
wire   [0:0] xor_ln56_fu_1516_p2;
wire   [63:0] rule_b_reg_attributes_7_fu_1529_p2;
wire   [63:0] rule_b_reg_attributes_7_fu_1529_p7;
wire   [1:0] sel_tmp7_fu_1521_p3;
wire   [63:0] rule_b_reg_attributes_4_fu_1549_p2;
wire   [63:0] rule_b_reg_attributes_4_fu_1549_p7;
wire   [63:0] rule_b_reg_attributes_5_fu_1569_p2;
wire   [63:0] rule_b_reg_attributes_5_fu_1569_p7;
wire   [63:0] rule_b_reg_attributes_6_fu_1589_p2;
wire   [63:0] rule_b_reg_attributes_6_fu_1589_p7;
wire   [63:0] rule_b_reg_objects_7_fu_1609_p2;
wire   [63:0] rule_b_reg_objects_7_fu_1609_p7;
wire   [63:0] rule_b_reg_objects_4_fu_1629_p2;
wire   [63:0] rule_b_reg_objects_4_fu_1629_p7;
wire   [63:0] rule_b_reg_objects_5_fu_1649_p2;
wire   [63:0] rule_b_reg_objects_5_fu_1649_p7;
wire   [63:0] rule_b_reg_objects_6_fu_1669_p2;
wire   [63:0] rule_b_reg_objects_6_fu_1669_p7;
wire   [63:0] rule_b_reg_subjects_7_fu_1689_p2;
wire   [63:0] rule_b_reg_subjects_7_fu_1689_p7;
wire   [63:0] rule_b_reg_subjects_4_fu_1709_p2;
wire   [63:0] rule_b_reg_subjects_4_fu_1709_p7;
wire   [63:0] rule_b_reg_subjects_5_fu_1729_p2;
wire   [63:0] rule_b_reg_subjects_5_fu_1729_p7;
wire   [63:0] rule_b_reg_subjects_6_fu_1749_p2;
wire   [63:0] rule_b_reg_subjects_6_fu_1749_p7;
wire   [63:0] rule_a_reg_attributes_6_fu_1348_p4;
wire   [63:0] rule_a_reg_attributes_5_fu_1338_p4;
wire   [63:0] rule_a_reg_attributes_4_fu_1328_p4;
wire   [63:0] rule_a_reg_attributes_7_fu_1318_p4;
wire   [63:0] rule_a_reg_objects_6_fu_1308_p4;
wire   [63:0] rule_a_reg_objects_5_fu_1298_p4;
wire   [63:0] rule_a_reg_objects_4_fu_1288_p4;
wire   [63:0] rule_a_reg_objects_7_fu_1278_p4;
wire   [63:0] rule_a_reg_subjects_5_fu_1268_p4;
wire   [63:0] rule_a_reg_subjects_4_fu_1258_p4;
wire   [63:0] rule_a_reg_subjects_7_fu_1248_p4;
wire   [63:0] rule_a_reg_subjects_6_fu_1244_p1;
wire   [31:0] rule_b_reg_required_provenance_val_fu_1853_p2;
wire   [31:0] rule_b_reg_required_provenance_val_fu_1853_p7;
wire   [31:0] rule_b_reg_required_states_val9_fu_1873_p2;
wire   [31:0] rule_b_reg_required_states_val9_fu_1873_p7;
wire   [31:0] trunc_ln58_1_fu_1368_p4;
wire   [31:0] trunc_ln58_s_fu_1358_p4;
wire   [0:0] xor_ln50_fu_2047_p2;
wire   [0:0] prov_ok_fu_2065_p2;
wire   [0:0] and_ln51_2_fu_2069_p2;
wire   [0:0] prov_ok_1_fu_2079_p2;
wire   [0:0] and_ln51_3_fu_2083_p2;
wire   [0:0] and_ln51_fu_2074_p2;
wire   [0:0] and_ln51_1_fu_2088_p2;
wire   [0:0] or_ln51_4_fu_2093_p2;
wire   [0:0] xor_ln50_1_fu_2099_p2;
wire   [0:0] and_ln51_4_fu_2105_p2;
wire   [0:0] or_ln50_fu_2053_p2;
wire   [0:0] and_ln51_5_fu_2111_p2;
wire   [0:0] found_1_fu_2125_p2;
wire   [0:0] found_1_fu_2125_p7;
wire   [1:0] found_1_fu_2125_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_888_p1;
wire   [1:0] tmp_fu_888_p3;
wire  signed [1:0] tmp_fu_888_p5;
wire  signed [1:0] tmp_fu_888_p7;
wire   [1:0] tmp_1_fu_922_p1;
wire   [1:0] tmp_1_fu_922_p3;
wire  signed [1:0] tmp_1_fu_922_p5;
wire  signed [1:0] tmp_1_fu_922_p7;
wire   [1:0] tmp_2_fu_1066_p1;
wire   [1:0] tmp_2_fu_1066_p3;
wire  signed [1:0] tmp_2_fu_1066_p5;
wire  signed [1:0] tmp_2_fu_1066_p7;
wire   [1:0] tmp_3_fu_1100_p1;
wire   [1:0] tmp_3_fu_1100_p3;
wire  signed [1:0] tmp_3_fu_1100_p5;
wire  signed [1:0] tmp_3_fu_1100_p7;
wire  signed [1:0] rule_b_reg_attributes_7_fu_1529_p1;
wire   [1:0] rule_b_reg_attributes_7_fu_1529_p3;
wire   [1:0] rule_b_reg_attributes_7_fu_1529_p5;
wire  signed [1:0] rule_b_reg_attributes_4_fu_1549_p1;
wire   [1:0] rule_b_reg_attributes_4_fu_1549_p3;
wire   [1:0] rule_b_reg_attributes_4_fu_1549_p5;
wire  signed [1:0] rule_b_reg_attributes_5_fu_1569_p1;
wire   [1:0] rule_b_reg_attributes_5_fu_1569_p3;
wire   [1:0] rule_b_reg_attributes_5_fu_1569_p5;
wire  signed [1:0] rule_b_reg_attributes_6_fu_1589_p1;
wire   [1:0] rule_b_reg_attributes_6_fu_1589_p3;
wire   [1:0] rule_b_reg_attributes_6_fu_1589_p5;
wire  signed [1:0] rule_b_reg_objects_7_fu_1609_p1;
wire   [1:0] rule_b_reg_objects_7_fu_1609_p3;
wire   [1:0] rule_b_reg_objects_7_fu_1609_p5;
wire  signed [1:0] rule_b_reg_objects_4_fu_1629_p1;
wire   [1:0] rule_b_reg_objects_4_fu_1629_p3;
wire   [1:0] rule_b_reg_objects_4_fu_1629_p5;
wire  signed [1:0] rule_b_reg_objects_5_fu_1649_p1;
wire   [1:0] rule_b_reg_objects_5_fu_1649_p3;
wire   [1:0] rule_b_reg_objects_5_fu_1649_p5;
wire  signed [1:0] rule_b_reg_objects_6_fu_1669_p1;
wire   [1:0] rule_b_reg_objects_6_fu_1669_p3;
wire   [1:0] rule_b_reg_objects_6_fu_1669_p5;
wire  signed [1:0] rule_b_reg_subjects_7_fu_1689_p1;
wire   [1:0] rule_b_reg_subjects_7_fu_1689_p3;
wire   [1:0] rule_b_reg_subjects_7_fu_1689_p5;
wire  signed [1:0] rule_b_reg_subjects_4_fu_1709_p1;
wire   [1:0] rule_b_reg_subjects_4_fu_1709_p3;
wire   [1:0] rule_b_reg_subjects_4_fu_1709_p5;
wire  signed [1:0] rule_b_reg_subjects_5_fu_1729_p1;
wire   [1:0] rule_b_reg_subjects_5_fu_1729_p3;
wire   [1:0] rule_b_reg_subjects_5_fu_1729_p5;
wire  signed [1:0] rule_b_reg_subjects_6_fu_1749_p1;
wire   [1:0] rule_b_reg_subjects_6_fu_1749_p3;
wire   [1:0] rule_b_reg_subjects_6_fu_1749_p5;
wire  signed [1:0] rule_b_reg_required_provenance_val_fu_1853_p1;
wire   [1:0] rule_b_reg_required_provenance_val_fu_1853_p3;
wire   [1:0] rule_b_reg_required_provenance_val_fu_1853_p5;
wire  signed [1:0] rule_b_reg_required_states_val9_fu_1873_p1;
wire   [1:0] rule_b_reg_required_states_val9_fu_1873_p3;
wire   [1:0] rule_b_reg_required_states_val9_fu_1873_p5;
wire  signed [1:0] found_1_fu_2125_p1;
wire   [1:0] found_1_fu_2125_p3;
wire   [1:0] found_1_fu_2125_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 p_fu_208 = 9'd0;
#0 rule_a_reg_required_states_val6_fu_212 = 32'd0;
#0 required_assign_fu_216 = 32'd0;
#0 rule_b_reg_required_states_val10_fu_220 = 32'd0;
#0 required_assign_1_fu_224 = 32'd0;
#0 rule_a_reg_subjects_fu_228 = 64'd0;
#0 rule_a_reg_subjects_1_fu_232 = 64'd0;
#0 rule_a_reg_subjects_2_fu_236 = 64'd0;
#0 rule_a_reg_subjects_3_fu_240 = 64'd0;
#0 rule_a_reg_objects_fu_244 = 64'd0;
#0 rule_a_reg_objects_1_fu_248 = 64'd0;
#0 rule_a_reg_objects_2_fu_252 = 64'd0;
#0 rule_a_reg_objects_3_fu_256 = 64'd0;
#0 rule_a_reg_attributes_fu_260 = 64'd0;
#0 rule_a_reg_attributes_1_fu_264 = 64'd0;
#0 rule_a_reg_attributes_2_fu_268 = 64'd0;
#0 rule_a_reg_attributes_3_fu_272 = 64'd0;
#0 rule_b_reg_subjects_fu_276 = 64'd0;
#0 rule_b_reg_subjects_1_fu_280 = 64'd0;
#0 rule_b_reg_subjects_2_fu_284 = 64'd0;
#0 rule_b_reg_subjects_3_fu_288 = 64'd0;
#0 rule_b_reg_objects_fu_292 = 64'd0;
#0 rule_b_reg_objects_1_fu_296 = 64'd0;
#0 rule_b_reg_objects_2_fu_300 = 64'd0;
#0 rule_b_reg_objects_3_fu_304 = 64'd0;
#0 rule_b_reg_attributes_fu_308 = 64'd0;
#0 rule_b_reg_attributes_1_fu_312 = 64'd0;
#0 rule_b_reg_attributes_2_fu_316 = 64'd0;
#0 rule_b_reg_attributes_3_fu_320 = 64'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U25(
    .din0(rule_a_reg_subjects_fu_228),
    .din1(rule_a_reg_subjects_1_fu_232),
    .din2(rule_a_reg_subjects_2_fu_236),
    .din3(rule_a_reg_subjects_3_fu_240),
    .def(tmp_fu_888_p9),
    .sel(trunc_ln3),
    .dout(tmp_fu_888_p11)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U26(
    .din0(rule_a_reg_objects_fu_244),
    .din1(rule_a_reg_objects_1_fu_248),
    .din2(rule_a_reg_objects_2_fu_252),
    .din3(rule_a_reg_objects_3_fu_256),
    .def(tmp_1_fu_922_p9),
    .sel(trunc_ln2),
    .dout(tmp_1_fu_922_p11)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U27(
    .din0(rule_b_reg_subjects_fu_276),
    .din1(rule_b_reg_subjects_1_fu_280),
    .din2(rule_b_reg_subjects_2_fu_284),
    .din3(rule_b_reg_subjects_3_fu_288),
    .def(tmp_2_fu_1066_p9),
    .sel(trunc_ln3),
    .dout(tmp_2_fu_1066_p11)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_9_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_9_2_64_1_1_U28(
    .din0(rule_b_reg_objects_fu_292),
    .din1(rule_b_reg_objects_1_fu_296),
    .din2(rule_b_reg_objects_2_fu_300),
    .din3(rule_b_reg_objects_3_fu_304),
    .def(tmp_3_fu_1100_p9),
    .sel(trunc_ln2),
    .dout(tmp_3_fu_1100_p11)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U29(
    .din0(rule_b_reg_attributes_7_fu_1529_p2),
    .din1(rule_b_reg_attributes_3_fu_320),
    .din2(64'd0),
    .def(rule_b_reg_attributes_7_fu_1529_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_attributes_7_fu_1529_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U30(
    .din0(rule_b_reg_attributes_4_fu_1549_p2),
    .din1(rule_b_reg_attributes_2_fu_316),
    .din2(64'd0),
    .def(rule_b_reg_attributes_4_fu_1549_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_attributes_4_fu_1549_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U31(
    .din0(rule_b_reg_attributes_5_fu_1569_p2),
    .din1(rule_b_reg_attributes_1_fu_312),
    .din2(64'd0),
    .def(rule_b_reg_attributes_5_fu_1569_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_attributes_5_fu_1569_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U32(
    .din0(rule_b_reg_attributes_6_fu_1589_p2),
    .din1(rule_b_reg_attributes_fu_308),
    .din2(64'd0),
    .def(rule_b_reg_attributes_6_fu_1589_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_attributes_6_fu_1589_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U33(
    .din0(rule_b_reg_objects_7_fu_1609_p2),
    .din1(rule_b_reg_objects_3_fu_304),
    .din2(64'd0),
    .def(rule_b_reg_objects_7_fu_1609_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_objects_7_fu_1609_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U34(
    .din0(rule_b_reg_objects_4_fu_1629_p2),
    .din1(rule_b_reg_objects_2_fu_300),
    .din2(64'd0),
    .def(rule_b_reg_objects_4_fu_1629_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_objects_4_fu_1629_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U35(
    .din0(rule_b_reg_objects_5_fu_1649_p2),
    .din1(rule_b_reg_objects_1_fu_296),
    .din2(64'd0),
    .def(rule_b_reg_objects_5_fu_1649_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_objects_5_fu_1649_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U36(
    .din0(rule_b_reg_objects_6_fu_1669_p2),
    .din1(rule_b_reg_objects_fu_292),
    .din2(64'd0),
    .def(rule_b_reg_objects_6_fu_1669_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_objects_6_fu_1669_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U37(
    .din0(rule_b_reg_subjects_7_fu_1689_p2),
    .din1(rule_b_reg_subjects_3_fu_288),
    .din2(64'd0),
    .def(rule_b_reg_subjects_7_fu_1689_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_subjects_7_fu_1689_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U38(
    .din0(rule_b_reg_subjects_4_fu_1709_p2),
    .din1(rule_b_reg_subjects_2_fu_284),
    .din2(64'd0),
    .def(rule_b_reg_subjects_4_fu_1709_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_subjects_4_fu_1709_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U39(
    .din0(rule_b_reg_subjects_5_fu_1729_p2),
    .din1(rule_b_reg_subjects_1_fu_280),
    .din2(64'd0),
    .def(rule_b_reg_subjects_5_fu_1729_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_subjects_5_fu_1729_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 64 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
sparsemux_7_2_64_1_1_U40(
    .din0(rule_b_reg_subjects_6_fu_1749_p2),
    .din1(rule_b_reg_subjects_fu_276),
    .din2(64'd0),
    .def(rule_b_reg_subjects_6_fu_1749_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_subjects_6_fu_1749_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U41(
    .din0(rule_b_reg_required_provenance_val_fu_1853_p2),
    .din1(required_assign_1_fu_224),
    .din2(32'd0),
    .def(rule_b_reg_required_provenance_val_fu_1853_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_required_provenance_val_fu_1853_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U42(
    .din0(rule_b_reg_required_states_val9_fu_1873_p2),
    .din1(rule_b_reg_required_states_val10_fu_220),
    .din2(32'd0),
    .def(rule_b_reg_required_states_val9_fu_1873_p7),
    .sel(sel_tmp7_fu_1521_p3),
    .dout(rule_b_reg_required_states_val9_fu_1873_p9)
);

(* dissolve_hierarchy = "yes" *) hngac_authorize_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U43(
    .din0(found_1_fu_2125_p2),
    .din1(1'd1),
    .din2(1'd0),
    .def(found_1_fu_2125_p7),
    .sel(found_1_fu_2125_p8),
    .dout(found_1_fu_2125_p9)
);

hngac_authorize_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_2416_pp0_iter1_reg == 1'd0))) begin
        found_reg_578 <= found_1_fu_2125_p9;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        found_reg_578 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln46_fu_751_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            p_fu_208 <= add_ln46_1_fu_757_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_208 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            required_assign_1_fu_224 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            required_assign_1_fu_224 <= rule_b_reg_required_provenance_val_fu_1853_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            required_assign_fu_216 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            required_assign_fu_216 <= rule_a_reg_required_provenance_val7_fu_1893_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_attributes_1_fu_264 <= rule_a_reg_attributes_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_attributes_1_fu_264 <= rule_a_reg_attributes_10_fu_1783_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_attributes_2_fu_268 <= rule_a_reg_attributes_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_attributes_2_fu_268 <= rule_a_reg_attributes_9_fu_1776_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_attributes_3_fu_272 <= rule_a_reg_attributes_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_attributes_3_fu_272 <= rule_a_reg_attributes_8_fu_1769_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_attributes_fu_260 <= rule_a_reg_attributes_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_attributes_fu_260 <= rule_a_reg_attributes_11_fu_1790_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_objects_1_fu_248 <= rule_a_reg_objects_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_objects_1_fu_248 <= rule_a_reg_objects_10_fu_1811_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_objects_2_fu_252 <= rule_a_reg_objects_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_objects_2_fu_252 <= rule_a_reg_objects_9_fu_1804_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_objects_3_fu_256 <= rule_a_reg_objects_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_objects_3_fu_256 <= rule_a_reg_objects_8_fu_1797_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_objects_fu_244 <= rule_a_reg_objects_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_objects_fu_244 <= rule_a_reg_objects_11_fu_1818_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_required_states_val6_fu_212 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_required_states_val6_fu_212 <= rule_a_reg_required_states_val5_fu_1900_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_subjects_1_fu_232 <= rule_a_reg_subjects_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_subjects_1_fu_232 <= rule_a_reg_subjects_10_fu_1839_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_subjects_2_fu_236 <= rule_a_reg_subjects_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_subjects_2_fu_236 <= rule_a_reg_subjects_9_fu_1832_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_subjects_3_fu_240 <= rule_a_reg_subjects_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_subjects_3_fu_240 <= rule_a_reg_subjects_8_fu_1825_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_a_reg_subjects_fu_228 <= rule_a_reg_subjects_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_a_reg_subjects_fu_228 <= rule_a_reg_subjects_11_fu_1846_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_attributes_1_fu_312 <= rule_b_reg_attributes_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_attributes_1_fu_312 <= rule_b_reg_attributes_5_fu_1569_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_attributes_2_fu_316 <= rule_b_reg_attributes_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_attributes_2_fu_316 <= rule_b_reg_attributes_4_fu_1549_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_attributes_3_fu_320 <= rule_b_reg_attributes_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_attributes_3_fu_320 <= rule_b_reg_attributes_7_fu_1529_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_attributes_fu_308 <= rule_b_reg_attributes_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_attributes_fu_308 <= rule_b_reg_attributes_6_fu_1589_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_objects_1_fu_296 <= rule_b_reg_objects_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_objects_1_fu_296 <= rule_b_reg_objects_5_fu_1649_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_objects_2_fu_300 <= rule_b_reg_objects_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_objects_2_fu_300 <= rule_b_reg_objects_4_fu_1629_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_objects_3_fu_304 <= rule_b_reg_objects_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_objects_3_fu_304 <= rule_b_reg_objects_7_fu_1609_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_objects_fu_292 <= rule_b_reg_objects_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_objects_fu_292 <= rule_b_reg_objects_6_fu_1669_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_required_states_val10_fu_220 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_required_states_val10_fu_220 <= rule_b_reg_required_states_val9_fu_1873_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_subjects_1_fu_280 <= rule_b_reg_subjects_1_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_subjects_1_fu_280 <= rule_b_reg_subjects_5_fu_1729_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_subjects_2_fu_284 <= rule_b_reg_subjects_2_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_subjects_2_fu_284 <= rule_b_reg_subjects_4_fu_1709_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_subjects_3_fu_288 <= rule_b_reg_subjects_3_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_subjects_3_fu_288 <= rule_b_reg_subjects_7_fu_1689_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rule_b_reg_subjects_fu_276 <= rule_b_reg_subjects_reload;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_2416 == 1'd0))) begin
            rule_b_reg_subjects_fu_276 <= rule_b_reg_subjects_6_fu_1749_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_2416_pp0_iter1_reg == 1'd0))) begin
        stage1_valid_reg_591 <= stage1_valid_1_reg_2420_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        stage1_valid_reg_591 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln46_reg_2416 <= icmp_ln46_fu_751_p2;
        icmp_ln46_reg_2416_pp0_iter1_reg <= icmp_ln46_reg_2416;
        icmp_ln59_reg_2446 <= icmp_ln59_fu_788_p2;
        icmp_ln95_1_reg_2481 <= icmp_ln95_1_fu_1209_p2;
        icmp_ln95_reg_2461 <= icmp_ln95_fu_1031_p2;
        icmp_ln98_1_reg_2486 <= icmp_ln98_1_fu_1220_p2;
        icmp_ln98_reg_2466 <= icmp_ln98_fu_1042_p2;
        stage1_valid_1_reg_2420_pp0_iter1_reg <= stage1_valid_1_reg_2420;
        state_ok_1_reg_2476 <= state_ok_1_fu_1203_p2;
        state_ok_reg_2456 <= state_ok_fu_1025_p2;
        xor_ln37_1_reg_2491 <= xor_ln37_1_fu_1238_p2;
        xor_ln37_reg_2471 <= xor_ln37_fu_1060_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stage1_valid_1_reg_2420 <= stage1_valid_1_fu_763_p2;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_751_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln46_reg_2416 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_p_1 = p_fu_208;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln46_reg_2416 == 1'd1))) begin
        found_out_ap_vld = 1'b1;
    end else begin
        found_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        policy_EN_A_local = 1'b1;
    end else begin
        policy_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        policy_EN_B_local = 1'b1;
    end else begin
        policy_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_1_fu_757_p2 = (ap_sig_allocacmp_p_1 + 9'd1);

assign and_ln28_1_fu_1089_p2 = (tmp_2_fu_1066_p11 & subj_mask);

assign and_ln28_fu_911_p2 = (tmp_fu_888_p11 & subj_mask);

assign and_ln29_1_fu_1123_p2 = (tmp_3_fu_1100_p11 & obj_mask);

assign and_ln29_fu_945_p2 = (tmp_1_fu_922_p11 & obj_mask);

assign and_ln31_1_fu_986_p2 = (icmp_ln33_fu_981_p2 & icmp_ln32_fu_971_p2);

assign and_ln31_2_fu_992_p2 = (icmp_ln31_fu_961_p2 & and_ln31_1_fu_986_p2);

assign and_ln31_3_fu_1134_p2 = (trunc_ln5 & rule_b_reg_attributes_fu_308);

assign and_ln31_4_fu_1164_p2 = (icmp_ln33_1_fu_1159_p2 & icmp_ln32_1_fu_1149_p2);

assign and_ln31_5_fu_1170_p2 = (icmp_ln31_1_fu_1139_p2 & and_ln31_4_fu_1164_p2);

assign and_ln31_fu_956_p2 = (trunc_ln5 & rule_a_reg_attributes_fu_260);

assign and_ln32_1_fu_1144_p2 = (trunc_ln6 & rule_b_reg_attributes_1_fu_312);

assign and_ln32_fu_966_p2 = (trunc_ln6 & rule_a_reg_attributes_1_fu_264);

assign and_ln33_1_fu_1154_p2 = (trunc_ln8 & rule_b_reg_attributes_2_fu_316);

assign and_ln33_fu_976_p2 = (trunc_ln8 & rule_a_reg_attributes_2_fu_268);

assign and_ln34_1_fu_1176_p2 = (trunc_ln9 & rule_b_reg_attributes_3_fu_320);

assign and_ln34_fu_998_p2 = (trunc_ln9 & rule_a_reg_attributes_3_fu_272);

assign and_ln35_1_fu_1198_p2 = (trunc_ln7 & rule_b_reg_required_states_val10_fu_220);

assign and_ln35_fu_1020_p2 = (trunc_ln7 & rule_a_reg_required_states_val6_fu_212);

assign and_ln51_1_fu_2088_p2 = (state_ok_1_reg_2476 & and_ln51_3_fu_2083_p2);

assign and_ln51_2_fu_2069_p2 = (xor_ln37_reg_2471 & prov_ok_fu_2065_p2);

assign and_ln51_3_fu_2083_p2 = (xor_ln37_1_reg_2491 & prov_ok_1_fu_2079_p2);

assign and_ln51_4_fu_2105_p2 = (xor_ln50_1_fu_2099_p2 & or_ln51_4_fu_2093_p2);

assign and_ln51_5_fu_2111_p2 = (stage1_valid_reg_591 & and_ln51_4_fu_2105_p2);

assign and_ln51_fu_2074_p2 = (state_ok_reg_2456 & and_ln51_2_fu_2069_p2);

assign and_ln59_fu_1512_p2 = (stage1_valid_1_reg_2420 & icmp_ln59_reg_2446);

assign and_ln98_1_fu_1215_p2 = (source_assign & required_assign_1_fu_224);

assign and_ln98_fu_1037_p2 = (source_assign & required_assign_fu_216);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_18_fu_1192_p2 = (not_and_ln31_5_fu_1186_p2 | icmp_ln34_1_fu_1181_p2);

assign empty_fu_1014_p2 = (not_and_ln31_2_fu_1008_p2 | icmp_ln34_fu_1003_p2);

assign found_1_fu_2125_p2 = (stage1_valid_reg_591 | found_reg_578);

assign found_1_fu_2125_p7 = 'bx;

assign found_1_fu_2125_p8 = {{or_ln50_fu_2053_p2}, {and_ln51_5_fu_2111_p2}};

assign found_out = found_reg_578;

assign icmp_ln31_1_fu_1139_p2 = ((and_ln31_3_fu_1134_p2 == trunc_ln5) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_961_p2 = ((and_ln31_fu_956_p2 == trunc_ln5) ? 1'b1 : 1'b0);

assign icmp_ln32_1_fu_1149_p2 = ((and_ln32_1_fu_1144_p2 == trunc_ln6) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_971_p2 = ((and_ln32_fu_966_p2 == trunc_ln6) ? 1'b1 : 1'b0);

assign icmp_ln33_1_fu_1159_p2 = ((and_ln33_1_fu_1154_p2 == trunc_ln8) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_981_p2 = ((and_ln33_fu_976_p2 == trunc_ln8) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_1181_p2 = ((and_ln34_1_fu_1176_p2 != trunc_ln9) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_1003_p2 = ((and_ln34_fu_998_p2 != trunc_ln9) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_751_p2 = ((ap_sig_allocacmp_p_1 == add_ln46) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_788_p2 = ((or_ln_fu_780_p3 < bounded_rule_count) ? 1'b1 : 1'b0);

assign icmp_ln95_1_fu_1209_p2 = ((required_assign_1_fu_224 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_1031_p2 = ((required_assign_fu_216 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln98_1_fu_1220_p2 = ((and_ln98_1_fu_1215_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_1042_p2 = ((and_ln98_fu_1037_p2 != 32'd0) ? 1'b1 : 1'b0);

assign not_and_ln31_2_fu_1008_p2 = (1'd1 ^ and_ln31_2_fu_992_p2);

assign not_and_ln31_5_fu_1186_p2 = (1'd1 ^ and_ln31_5_fu_1170_p2);

assign obj_ok_1_fu_1128_p2 = ((and_ln29_1_fu_1123_p2 == 64'd0) ? 1'b1 : 1'b0);

assign obj_ok_fu_950_p2 = ((and_ln29_fu_945_p2 == 64'd0) ? 1'b1 : 1'b0);

assign or_ln50_fu_2053_p2 = (xor_ln50_fu_2047_p2 | found_reg_578);

assign or_ln51_1_fu_1232_p2 = (subj_ok_1_fu_1094_p2 | or_ln51_3_fu_1226_p2);

assign or_ln51_2_fu_1048_p2 = (obj_ok_fu_950_p2 | empty_fu_1014_p2);

assign or_ln51_3_fu_1226_p2 = (obj_ok_1_fu_1128_p2 | empty_18_fu_1192_p2);

assign or_ln51_4_fu_2093_p2 = (and_ln51_fu_2074_p2 | and_ln51_1_fu_2088_p2);

assign or_ln51_fu_1054_p2 = (subj_ok_fu_916_p2 | or_ln51_2_fu_1048_p2);

assign or_ln_fu_780_p3 = {{ap_sig_allocacmp_p_1}, {1'd1}};

assign policy_Addr_A = policy_Addr_A_local;

assign policy_Addr_A_local = policy_Addr_A_orig << 32'd7;

assign policy_Addr_A_orig = zext_ln60_fu_794_p1;

assign policy_Addr_B = policy_Addr_B_local;

assign policy_Addr_B_local = policy_Addr_B_orig << 32'd7;

assign policy_Addr_B_orig = zext_ln58_fu_775_p1;

assign policy_Din_A = 1024'd0;

assign policy_Din_B = 1024'd0;

assign policy_EN_A = policy_EN_A_local;

assign policy_EN_B = policy_EN_B_local;

assign policy_WEN_A = 128'd0;

assign policy_WEN_B = 128'd0;

assign prov_ok_1_fu_2079_p2 = (icmp_ln98_1_reg_2486 | icmp_ln95_1_reg_2481);

assign prov_ok_fu_2065_p2 = (icmp_ln98_reg_2466 | icmp_ln95_reg_2461);

assign rule_a_reg_attributes_10_fu_1783_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_attributes_4_fu_1328_p4 : rule_a_reg_attributes_1_fu_264);

assign rule_a_reg_attributes_11_fu_1790_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_attributes_7_fu_1318_p4 : rule_a_reg_attributes_fu_260);

assign rule_a_reg_attributes_4_fu_1328_p4 = {{policy_Dout_B[639:576]}};

assign rule_a_reg_attributes_5_fu_1338_p4 = {{policy_Dout_B[703:640]}};

assign rule_a_reg_attributes_6_fu_1348_p4 = {{policy_Dout_B[767:704]}};

assign rule_a_reg_attributes_7_fu_1318_p4 = {{policy_Dout_B[575:512]}};

assign rule_a_reg_attributes_8_fu_1769_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_attributes_6_fu_1348_p4 : rule_a_reg_attributes_3_fu_272);

assign rule_a_reg_attributes_9_fu_1776_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_attributes_5_fu_1338_p4 : rule_a_reg_attributes_2_fu_268);

assign rule_a_reg_objects_10_fu_1811_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_objects_4_fu_1288_p4 : rule_a_reg_objects_1_fu_248);

assign rule_a_reg_objects_11_fu_1818_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_objects_7_fu_1278_p4 : rule_a_reg_objects_fu_244);

assign rule_a_reg_objects_4_fu_1288_p4 = {{policy_Dout_B[383:320]}};

assign rule_a_reg_objects_5_fu_1298_p4 = {{policy_Dout_B[447:384]}};

assign rule_a_reg_objects_6_fu_1308_p4 = {{policy_Dout_B[511:448]}};

assign rule_a_reg_objects_7_fu_1278_p4 = {{policy_Dout_B[319:256]}};

assign rule_a_reg_objects_8_fu_1797_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_objects_6_fu_1308_p4 : rule_a_reg_objects_3_fu_256);

assign rule_a_reg_objects_9_fu_1804_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_objects_5_fu_1298_p4 : rule_a_reg_objects_2_fu_252);

assign rule_a_reg_required_provenance_val7_fu_1893_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? trunc_ln58_1_fu_1368_p4 : required_assign_fu_216);

assign rule_a_reg_required_states_val5_fu_1900_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? trunc_ln58_s_fu_1358_p4 : rule_a_reg_required_states_val6_fu_212);

assign rule_a_reg_subjects_10_fu_1839_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_subjects_7_fu_1248_p4 : rule_a_reg_subjects_1_fu_232);

assign rule_a_reg_subjects_11_fu_1846_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_subjects_6_fu_1244_p1 : rule_a_reg_subjects_fu_228);

assign rule_a_reg_subjects_4_fu_1258_p4 = {{policy_Dout_B[191:128]}};

assign rule_a_reg_subjects_5_fu_1268_p4 = {{policy_Dout_B[255:192]}};

assign rule_a_reg_subjects_6_fu_1244_p1 = policy_Dout_B[63:0];

assign rule_a_reg_subjects_7_fu_1248_p4 = {{policy_Dout_B[127:64]}};

assign rule_a_reg_subjects_8_fu_1825_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_subjects_5_fu_1268_p4 : rule_a_reg_subjects_3_fu_240);

assign rule_a_reg_subjects_9_fu_1832_p3 = ((stage1_valid_1_reg_2420[0:0] == 1'b1) ? rule_a_reg_subjects_4_fu_1258_p4 : rule_a_reg_subjects_2_fu_236);

assign rule_b_reg_attributes_4_fu_1549_p2 = {{policy_Dout_A[703:640]}};

assign rule_b_reg_attributes_4_fu_1549_p7 = 'bx;

assign rule_b_reg_attributes_5_fu_1569_p2 = {{policy_Dout_A[639:576]}};

assign rule_b_reg_attributes_5_fu_1569_p7 = 'bx;

assign rule_b_reg_attributes_6_fu_1589_p2 = {{policy_Dout_A[575:512]}};

assign rule_b_reg_attributes_6_fu_1589_p7 = 'bx;

assign rule_b_reg_attributes_7_fu_1529_p2 = {{policy_Dout_A[767:704]}};

assign rule_b_reg_attributes_7_fu_1529_p7 = 'bx;

assign rule_b_reg_objects_4_fu_1629_p2 = {{policy_Dout_A[447:384]}};

assign rule_b_reg_objects_4_fu_1629_p7 = 'bx;

assign rule_b_reg_objects_5_fu_1649_p2 = {{policy_Dout_A[383:320]}};

assign rule_b_reg_objects_5_fu_1649_p7 = 'bx;

assign rule_b_reg_objects_6_fu_1669_p2 = {{policy_Dout_A[319:256]}};

assign rule_b_reg_objects_6_fu_1669_p7 = 'bx;

assign rule_b_reg_objects_7_fu_1609_p2 = {{policy_Dout_A[511:448]}};

assign rule_b_reg_objects_7_fu_1609_p7 = 'bx;

assign rule_b_reg_required_provenance_val_fu_1853_p2 = {{policy_Dout_A[831:800]}};

assign rule_b_reg_required_provenance_val_fu_1853_p7 = 'bx;

assign rule_b_reg_required_states_val9_fu_1873_p2 = {{policy_Dout_A[799:768]}};

assign rule_b_reg_required_states_val9_fu_1873_p7 = 'bx;

assign rule_b_reg_subjects_4_fu_1709_p2 = {{policy_Dout_A[191:128]}};

assign rule_b_reg_subjects_4_fu_1709_p7 = 'bx;

assign rule_b_reg_subjects_5_fu_1729_p2 = {{policy_Dout_A[127:64]}};

assign rule_b_reg_subjects_5_fu_1729_p7 = 'bx;

assign rule_b_reg_subjects_6_fu_1749_p2 = policy_Dout_A[63:0];

assign rule_b_reg_subjects_6_fu_1749_p7 = 'bx;

assign rule_b_reg_subjects_7_fu_1689_p2 = {{policy_Dout_A[255:192]}};

assign rule_b_reg_subjects_7_fu_1689_p7 = 'bx;

assign sel_tmp7_fu_1521_p3 = {{and_ln59_fu_1512_p2}, {xor_ln56_fu_1516_p2}};

assign shl_ln57_fu_769_p2 = ap_sig_allocacmp_p_1 << 9'd1;

assign stage1_valid_1_fu_763_p2 = ((ap_sig_allocacmp_p_1 < trunc_ln4) ? 1'b1 : 1'b0);

assign state_ok_1_fu_1203_p2 = ((and_ln35_1_fu_1198_p2 == rule_b_reg_required_states_val10_fu_220) ? 1'b1 : 1'b0);

assign state_ok_fu_1025_p2 = ((and_ln35_fu_1020_p2 == rule_a_reg_required_states_val6_fu_212) ? 1'b1 : 1'b0);

assign subj_ok_1_fu_1094_p2 = ((and_ln28_1_fu_1089_p2 == 64'd0) ? 1'b1 : 1'b0);

assign subj_ok_fu_916_p2 = ((and_ln28_fu_911_p2 == 64'd0) ? 1'b1 : 1'b0);

assign tmp_1_fu_922_p9 = 'bx;

assign tmp_2_fu_1066_p9 = 'bx;

assign tmp_3_fu_1100_p9 = 'bx;

assign tmp_fu_888_p9 = 'bx;

assign trunc_ln58_1_fu_1368_p4 = {{policy_Dout_B[831:800]}};

assign trunc_ln58_s_fu_1358_p4 = {{policy_Dout_B[799:768]}};

assign xor_ln37_1_fu_1238_p2 = (or_ln51_1_fu_1232_p2 ^ 1'd1);

assign xor_ln37_fu_1060_p2 = (or_ln51_fu_1054_p2 ^ 1'd1);

assign xor_ln50_1_fu_2099_p2 = (found_reg_578 ^ 1'd1);

assign xor_ln50_fu_2047_p2 = (stage1_valid_reg_591 ^ 1'd1);

assign xor_ln56_fu_1516_p2 = (stage1_valid_1_reg_2420 ^ 1'd1);

assign zext_ln58_fu_775_p1 = shl_ln57_fu_769_p2;

assign zext_ln60_fu_794_p1 = or_ln_fu_780_p3;

endmodule //hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1
