// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hngac_authorize_hngac_authorize,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.965000,HLS_SYN_LAT=72,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2679,HLS_SYN_LUT=5104,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module hngac_authorize (
        ap_clk,
        ap_rst_n,
        policy_Addr_A,
        policy_EN_A,
        policy_WEN_A,
        policy_Din_A,
        policy_Dout_A,
        policy_Clk_A,
        policy_Rst_A,
        policy_Addr_B,
        policy_EN_B,
        policy_WEN_B,
        policy_Din_B,
        policy_Dout_B,
        policy_Clk_B,
        policy_Rst_B,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] policy_Addr_A;
output   policy_EN_A;
output  [127:0] policy_WEN_A;
output  [1023:0] policy_Din_A;
input  [1023:0] policy_Dout_A;
output   policy_Clk_A;
output   policy_Rst_A;
output  [31:0] policy_Addr_B;
output   policy_EN_B;
output  [127:0] policy_WEN_B;
output  [1023:0] policy_Din_B;
input  [1023:0] policy_Dout_B;
output   policy_Clk_B;
output   policy_Rst_B;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] rule_count;
wire   [383:0] request;
wire   [0:0] icmp_ln14_fu_355_p2;
reg   [0:0] icmp_ln14_reg_776;
wire   [0:0] icmp_ln14_1_fu_371_p2;
reg   [0:0] icmp_ln14_1_reg_780;
wire   [5:0] trunc_ln21_fu_377_p1;
reg   [5:0] trunc_ln21_reg_784;
reg   [5:0] trunc_ln1_reg_789;
reg   [1:0] trunc_ln2_reg_794;
reg   [1:0] trunc_ln3_reg_799;
wire   [9:0] bounded_rule_count_fu_417_p3;
reg   [9:0] bounded_rule_count_reg_804;
reg   [63:0] trunc_ln5_reg_810;
reg   [63:0] trunc_ln6_reg_815;
reg   [31:0] trunc_ln7_reg_820;
reg   [31:0] source_assign_reg_825;
reg   [63:0] trunc_ln8_reg_830;
reg   [63:0] trunc_ln9_reg_835;
wire   [63:0] subj_mask_fu_488_p2;
reg   [63:0] subj_mask_reg_840;
wire    ap_CS_fsm_state2;
wire   [63:0] obj_mask_fu_497_p2;
reg   [63:0] obj_mask_reg_845;
wire   [8:0] trunc_ln4_fu_604_p4;
reg   [8:0] trunc_ln4_reg_922;
wire    ap_CS_fsm_state3;
wire   [8:0] add_ln46_fu_615_p2;
reg   [8:0] add_ln46_reg_927;
wire    grp_hngac_authorize_Pipeline_1_fu_249_ap_start;
wire    grp_hngac_authorize_Pipeline_1_fu_249_ap_done;
wire    grp_hngac_authorize_Pipeline_1_fu_249_ap_idle;
wire    grp_hngac_authorize_Pipeline_1_fu_249_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out;
wire    grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out;
wire    grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out;
wire    grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out;
wire    grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_2_fu_257_ap_start;
wire    grp_hngac_authorize_Pipeline_2_fu_257_ap_done;
wire    grp_hngac_authorize_Pipeline_2_fu_257_ap_idle;
wire    grp_hngac_authorize_Pipeline_2_fu_257_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out;
wire    grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out;
wire    grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out;
wire    grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out;
wire    grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_3_fu_265_ap_start;
wire    grp_hngac_authorize_Pipeline_3_fu_265_ap_done;
wire    grp_hngac_authorize_Pipeline_3_fu_265_ap_idle;
wire    grp_hngac_authorize_Pipeline_3_fu_265_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out;
wire    grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out;
wire    grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out;
wire    grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out;
wire    grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_4_fu_273_ap_start;
wire    grp_hngac_authorize_Pipeline_4_fu_273_ap_done;
wire    grp_hngac_authorize_Pipeline_4_fu_273_ap_idle;
wire    grp_hngac_authorize_Pipeline_4_fu_273_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out;
wire    grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out;
wire    grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out;
wire    grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out;
wire    grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_5_fu_281_ap_start;
wire    grp_hngac_authorize_Pipeline_5_fu_281_ap_done;
wire    grp_hngac_authorize_Pipeline_5_fu_281_ap_idle;
wire    grp_hngac_authorize_Pipeline_5_fu_281_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out;
wire    grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out;
wire    grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out;
wire    grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out;
wire    grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_6_fu_289_ap_start;
wire    grp_hngac_authorize_Pipeline_6_fu_289_ap_done;
wire    grp_hngac_authorize_Pipeline_6_fu_289_ap_idle;
wire    grp_hngac_authorize_Pipeline_6_fu_289_ap_ready;
wire   [63:0] grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out;
wire    grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out;
wire    grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out;
wire    grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out_ap_vld;
wire   [63:0] grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out;
wire    grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out_ap_vld;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_idle;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready;
wire   [31:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A;
wire   [127:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_A;
wire   [1023:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_A;
wire   [31:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B;
wire   [127:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_B;
wire   [1023:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_B;
wire   [0:0] grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out;
wire    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out_ap_vld;
reg   [0:0] ap_phi_mux_retval_0_phi_fu_242_p4;
reg   [0:0] retval_0_reg_238;
wire    ap_CS_fsm_state5;
reg    grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg;
reg    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [7:0] tmp_fu_345_p4;
wire   [7:0] tmp_1_fu_361_p4;
wire   [0:0] icmp_ln19_fu_411_p2;
wire   [9:0] empty_fu_341_p1;
wire   [63:0] zext_ln22_fu_485_p1;
wire   [63:0] zext_ln24_fu_494_p1;
wire   [9:0] add_ln40_fu_583_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;
wire   [0:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg = 1'b0;
#0 grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg = 1'b0;
end

hngac_authorize_hngac_authorize_Pipeline_1 grp_hngac_authorize_Pipeline_1_fu_249(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_1_fu_249_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_1_fu_249_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_1_fu_249_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_1_fu_249_ap_ready),
    .rule_a_reg_subjects_3_out(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out),
    .rule_a_reg_subjects_3_out_ap_vld(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out_ap_vld),
    .rule_a_reg_subjects_2_out(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out),
    .rule_a_reg_subjects_2_out_ap_vld(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out_ap_vld),
    .rule_a_reg_subjects_1_out(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out),
    .rule_a_reg_subjects_1_out_ap_vld(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out_ap_vld),
    .rule_a_reg_subjects_out(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out),
    .rule_a_reg_subjects_out_ap_vld(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_2 grp_hngac_authorize_Pipeline_2_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_2_fu_257_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_2_fu_257_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_2_fu_257_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_2_fu_257_ap_ready),
    .rule_a_reg_objects_3_out(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out),
    .rule_a_reg_objects_3_out_ap_vld(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out_ap_vld),
    .rule_a_reg_objects_2_out(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out),
    .rule_a_reg_objects_2_out_ap_vld(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out_ap_vld),
    .rule_a_reg_objects_1_out(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out),
    .rule_a_reg_objects_1_out_ap_vld(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out_ap_vld),
    .rule_a_reg_objects_out(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out),
    .rule_a_reg_objects_out_ap_vld(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_3 grp_hngac_authorize_Pipeline_3_fu_265(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_3_fu_265_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_3_fu_265_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_3_fu_265_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_3_fu_265_ap_ready),
    .rule_a_reg_attributes_3_out(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out),
    .rule_a_reg_attributes_3_out_ap_vld(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out_ap_vld),
    .rule_a_reg_attributes_2_out(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out),
    .rule_a_reg_attributes_2_out_ap_vld(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out_ap_vld),
    .rule_a_reg_attributes_1_out(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out),
    .rule_a_reg_attributes_1_out_ap_vld(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out_ap_vld),
    .rule_a_reg_attributes_out(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out),
    .rule_a_reg_attributes_out_ap_vld(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_4 grp_hngac_authorize_Pipeline_4_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_4_fu_273_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_4_fu_273_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_4_fu_273_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_4_fu_273_ap_ready),
    .rule_b_reg_subjects_3_out(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out),
    .rule_b_reg_subjects_3_out_ap_vld(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out_ap_vld),
    .rule_b_reg_subjects_2_out(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out),
    .rule_b_reg_subjects_2_out_ap_vld(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out_ap_vld),
    .rule_b_reg_subjects_1_out(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out),
    .rule_b_reg_subjects_1_out_ap_vld(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out_ap_vld),
    .rule_b_reg_subjects_out(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out),
    .rule_b_reg_subjects_out_ap_vld(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_5 grp_hngac_authorize_Pipeline_5_fu_281(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_5_fu_281_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_5_fu_281_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_5_fu_281_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_5_fu_281_ap_ready),
    .rule_b_reg_objects_3_out(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out),
    .rule_b_reg_objects_3_out_ap_vld(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out_ap_vld),
    .rule_b_reg_objects_2_out(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out),
    .rule_b_reg_objects_2_out_ap_vld(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out_ap_vld),
    .rule_b_reg_objects_1_out(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out),
    .rule_b_reg_objects_1_out_ap_vld(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out_ap_vld),
    .rule_b_reg_objects_out(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out),
    .rule_b_reg_objects_out_ap_vld(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_6 grp_hngac_authorize_Pipeline_6_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_6_fu_289_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_6_fu_289_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_6_fu_289_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_6_fu_289_ap_ready),
    .rule_b_reg_attributes_3_out(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out),
    .rule_b_reg_attributes_3_out_ap_vld(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out_ap_vld),
    .rule_b_reg_attributes_2_out(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out),
    .rule_b_reg_attributes_2_out_ap_vld(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out_ap_vld),
    .rule_b_reg_attributes_1_out(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out),
    .rule_b_reg_attributes_1_out_ap_vld(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out_ap_vld),
    .rule_b_reg_attributes_out(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out),
    .rule_b_reg_attributes_out_ap_vld(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out_ap_vld)
);

hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1 grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start),
    .ap_done(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done),
    .ap_idle(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_idle),
    .ap_ready(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready),
    .rule_b_reg_attributes_3_reload(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out),
    .rule_b_reg_attributes_2_reload(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out),
    .rule_b_reg_attributes_1_reload(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out),
    .rule_b_reg_attributes_reload(grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out),
    .rule_b_reg_objects_3_reload(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out),
    .rule_b_reg_objects_2_reload(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out),
    .rule_b_reg_objects_1_reload(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out),
    .rule_b_reg_objects_reload(grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out),
    .rule_b_reg_subjects_3_reload(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out),
    .rule_b_reg_subjects_2_reload(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out),
    .rule_b_reg_subjects_1_reload(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out),
    .rule_b_reg_subjects_reload(grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out),
    .rule_a_reg_attributes_3_reload(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out),
    .rule_a_reg_attributes_2_reload(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out),
    .rule_a_reg_attributes_1_reload(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out),
    .rule_a_reg_attributes_reload(grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out),
    .rule_a_reg_objects_3_reload(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out),
    .rule_a_reg_objects_2_reload(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out),
    .rule_a_reg_objects_1_reload(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out),
    .rule_a_reg_objects_reload(grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out),
    .rule_a_reg_subjects_3_reload(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out),
    .rule_a_reg_subjects_2_reload(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out),
    .rule_a_reg_subjects_1_reload(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out),
    .rule_a_reg_subjects_reload(grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out),
    .add_ln46(add_ln46_reg_927),
    .trunc_ln3(trunc_ln3_reg_799),
    .subj_mask(subj_mask_reg_840),
    .trunc_ln2(trunc_ln2_reg_794),
    .obj_mask(obj_mask_reg_845),
    .trunc_ln5(trunc_ln5_reg_810),
    .trunc_ln6(trunc_ln6_reg_815),
    .trunc_ln8(trunc_ln8_reg_830),
    .trunc_ln9(trunc_ln9_reg_835),
    .trunc_ln7(trunc_ln7_reg_820),
    .source_assign(source_assign_reg_825),
    .trunc_ln4(trunc_ln4_reg_922),
    .policy_Addr_A(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A),
    .policy_EN_A(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A),
    .policy_WEN_A(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_A),
    .policy_Din_A(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_A),
    .policy_Dout_A(policy_Dout_A),
    .policy_Addr_B(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B),
    .policy_EN_B(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B),
    .policy_WEN_B(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_B),
    .policy_Din_B(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_B),
    .policy_Dout_B(policy_Dout_B),
    .bounded_rule_count(bounded_rule_count_reg_804),
    .found_out(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out),
    .found_out_ap_vld(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out_ap_vld)
);

hngac_authorize_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(ap_phi_mux_retval_0_phi_fu_242_p4),
    .rule_count(rule_count),
    .request(request)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_1_fu_249_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_2_fu_257_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_3_fu_265_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_4_fu_273_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_5_fu_281_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_6_fu_289_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= 1'b1;
        end else if ((grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready == 1'b1)) begin
            grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_1_reg_780 == 1'd1) & (icmp_ln14_reg_776 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        retval_0_reg_238 <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((icmp_ln14_1_fu_371_p2 == 1'd0) | (icmp_ln14_fu_355_p2 == 1'd0)))) begin
        retval_0_reg_238 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln46_reg_927 <= add_ln46_fu_615_p2;
        trunc_ln4_reg_922 <= {{add_ln40_fu_583_p2[9:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bounded_rule_count_reg_804 <= bounded_rule_count_fu_417_p3;
        icmp_ln14_1_reg_780 <= icmp_ln14_1_fu_371_p2;
        icmp_ln14_reg_776 <= icmp_ln14_fu_355_p2;
        source_assign_reg_825 <= {{request[383:352]}};
        trunc_ln1_reg_789 <= {{request[21:16]}};
        trunc_ln21_reg_784 <= trunc_ln21_fu_377_p1;
        trunc_ln2_reg_794 <= {{request[23:22]}};
        trunc_ln3_reg_799 <= {{request[7:6]}};
        trunc_ln5_reg_810 <= {{request[127:64]}};
        trunc_ln6_reg_815 <= {{request[191:128]}};
        trunc_ln7_reg_820 <= {{request[351:320]}};
        trunc_ln8_reg_830 <= {{request[255:192]}};
        trunc_ln9_reg_835 <= {{request[319:256]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        obj_mask_reg_845 <= obj_mask_fu_497_p2;
        subj_mask_reg_840 <= subj_mask_fu_488_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_1_reg_780 == 1'd1) & (icmp_ln14_reg_776 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_retval_0_phi_fu_242_p4 = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out;
    end else begin
        ap_phi_mux_retval_0_phi_fu_242_p4 = retval_0_reg_238;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((icmp_ln14_1_fu_371_p2 == 1'd0) | (icmp_ln14_fu_355_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((icmp_ln14_1_fu_371_p2 == 1'd1) & (icmp_ln14_fu_355_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln40_fu_583_p2 = (bounded_rule_count_reg_804 + 10'd1);

assign add_ln46_fu_615_p2 = (trunc_ln4_fu_604_p4 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_hngac_authorize_Pipeline_1_fu_249_ap_done == 1'b0) | (grp_hngac_authorize_Pipeline_6_fu_289_ap_done == 1'b0) | (grp_hngac_authorize_Pipeline_5_fu_281_ap_done == 1'b0) | (grp_hngac_authorize_Pipeline_4_fu_273_ap_done == 1'b0) | (grp_hngac_authorize_Pipeline_3_fu_265_ap_done == 1'b0) | (grp_hngac_authorize_Pipeline_2_fu_257_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bounded_rule_count_fu_417_p3 = ((icmp_ln19_fu_411_p2[0:0] == 1'b1) ? 10'd512 : empty_fu_341_p1);

assign empty_fu_341_p1 = rule_count[9:0];

assign grp_hngac_authorize_Pipeline_1_fu_249_ap_start = grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg;

assign grp_hngac_authorize_Pipeline_2_fu_257_ap_start = grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg;

assign grp_hngac_authorize_Pipeline_3_fu_265_ap_start = grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg;

assign grp_hngac_authorize_Pipeline_4_fu_273_ap_start = grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg;

assign grp_hngac_authorize_Pipeline_5_fu_281_ap_start = grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg;

assign grp_hngac_authorize_Pipeline_6_fu_289_ap_start = grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg;

assign grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg;

assign icmp_ln14_1_fu_371_p2 = ((tmp_1_fu_361_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_355_p2 = ((tmp_fu_345_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_411_p2 = ((rule_count > 16'd512) ? 1'b1 : 1'b0);

assign obj_mask_fu_497_p2 = 64'd1 << zext_ln24_fu_494_p1;

assign policy_Addr_A = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A;

assign policy_Addr_B = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B;

assign policy_Clk_A = ap_clk;

assign policy_Clk_B = ap_clk;

assign policy_Din_A = 1024'd0;

assign policy_Din_B = 1024'd0;

assign policy_EN_A = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A;

assign policy_EN_B = grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B;

assign policy_Rst_A = ap_rst_n_inv;

assign policy_Rst_B = ap_rst_n_inv;

assign policy_WEN_A = 128'd0;

assign policy_WEN_B = 128'd0;

assign subj_mask_fu_488_p2 = 64'd1 << zext_ln22_fu_485_p1;

assign tmp_1_fu_361_p4 = {{request[31:24]}};

assign tmp_fu_345_p4 = {{request[15:8]}};

assign trunc_ln21_fu_377_p1 = request[5:0];

assign trunc_ln4_fu_604_p4 = {{add_ln40_fu_583_p2[9:1]}};

assign zext_ln22_fu_485_p1 = trunc_ln21_reg_784;

assign zext_ln24_fu_494_p1 = trunc_ln1_reg_789;

endmodule //hngac_authorize
