-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rule_b_reg_attributes_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_attributes_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_attributes_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_attributes_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_objects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_objects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_objects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_objects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_subjects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_subjects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_subjects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_b_reg_subjects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_attributes_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_attributes_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_attributes_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_attributes_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_objects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_objects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_objects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_objects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_subjects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_subjects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_subjects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    rule_a_reg_subjects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
    add_ln46 : IN STD_LOGIC_VECTOR (8 downto 0);
    trunc_ln3 : IN STD_LOGIC_VECTOR (1 downto 0);
    subj_mask : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln2 : IN STD_LOGIC_VECTOR (1 downto 0);
    obj_mask : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln5 : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln6 : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln8 : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln9 : IN STD_LOGIC_VECTOR (63 downto 0);
    trunc_ln7 : IN STD_LOGIC_VECTOR (31 downto 0);
    source_assign : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln4 : IN STD_LOGIC_VECTOR (8 downto 0);
    policy_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    policy_EN_A : OUT STD_LOGIC;
    policy_WEN_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    policy_Din_A : OUT STD_LOGIC_VECTOR (1023 downto 0);
    policy_Dout_A : IN STD_LOGIC_VECTOR (1023 downto 0);
    policy_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    policy_EN_B : OUT STD_LOGIC;
    policy_WEN_B : OUT STD_LOGIC_VECTOR (127 downto 0);
    policy_Din_B : OUT STD_LOGIC_VECTOR (1023 downto 0);
    policy_Dout_B : IN STD_LOGIC_VECTOR (1023 downto 0);
    bounded_rule_count : IN STD_LOGIC_VECTOR (9 downto 0);
    found_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    found_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";
    constant ap_const_lv32_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000000";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_2BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010111111";
    constant ap_const_lv32_2C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011000000";
    constant ap_const_lv32_2FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011111111";
    constant ap_const_lv32_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100000000";
    constant ap_const_lv32_31F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100011111";
    constant ap_const_lv32_320 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100100000";
    constant ap_const_lv32_33F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100111111";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln46_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal found_reg_578 : STD_LOGIC_VECTOR (0 downto 0);
    signal stage1_valid_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln46_reg_2416 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_2416_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal stage1_valid_1_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal stage1_valid_1_reg_2420 : STD_LOGIC_VECTOR (0 downto 0);
    signal stage1_valid_1_reg_2420_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_reg_2446 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_ok_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_ok_reg_2456 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_fu_1031_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_reg_2461 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_reg_2466 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_fu_1060_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_reg_2471 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_ok_1_fu_1203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_ok_1_reg_2476 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_1_fu_1209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_1_reg_2481 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_1_fu_1220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_1_reg_2486 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_1_fu_1238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_1_reg_2491 : STD_LOGIC_VECTOR (0 downto 0);
    signal found_1_fu_2125_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln58_fu_775_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_fu_794_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_fu_208 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln46_1_fu_757_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_p_1 : STD_LOGIC_VECTOR (8 downto 0);
    signal rule_a_reg_required_states_val6_fu_212 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rule_a_reg_required_states_val5_fu_1900_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal required_assign_fu_216 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rule_a_reg_required_provenance_val7_fu_1893_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rule_b_reg_required_states_val10_fu_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rule_b_reg_required_states_val9_fu_1873_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal required_assign_1_fu_224 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rule_b_reg_required_provenance_val_fu_1853_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal rule_a_reg_subjects_fu_228 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_subjects_11_fu_1846_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_1_fu_232 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_subjects_10_fu_1839_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_2_fu_236 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_subjects_9_fu_1832_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_3_fu_240 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_subjects_8_fu_1825_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_fu_244 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_objects_11_fu_1818_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_1_fu_248 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_objects_10_fu_1811_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_2_fu_252 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_objects_9_fu_1804_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_3_fu_256 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_objects_8_fu_1797_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_fu_260 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_attributes_11_fu_1790_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_1_fu_264 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_attributes_10_fu_1783_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_2_fu_268 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_attributes_9_fu_1776_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_3_fu_272 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_a_reg_attributes_8_fu_1769_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_fu_276 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_subjects_6_fu_1749_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_1_fu_280 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_subjects_5_fu_1729_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_2_fu_284 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_subjects_4_fu_1709_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_3_fu_288 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_subjects_7_fu_1689_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_fu_292 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_objects_6_fu_1669_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_1_fu_296 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_objects_5_fu_1649_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_2_fu_300 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_objects_4_fu_1629_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_3_fu_304 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_objects_7_fu_1609_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_fu_308 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_attributes_6_fu_1589_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_1_fu_312 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_attributes_5_fu_1569_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_2_fu_316 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_attributes_4_fu_1549_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_3_fu_320 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rule_b_reg_attributes_7_fu_1529_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal policy_EN_B_local : STD_LOGIC;
    signal policy_Addr_B_local : STD_LOGIC_VECTOR (31 downto 0);
    signal policy_Addr_B_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal policy_EN_A_local : STD_LOGIC;
    signal policy_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal policy_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln57_fu_769_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_780_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_888_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_888_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln28_fu_911_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_922_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_922_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln29_fu_945_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln31_fu_956_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln32_fu_966_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln33_fu_976_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln32_fu_971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln31_1_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_fu_961_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_fu_998_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln31_2_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_and_ln31_2_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_fu_1020_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln98_fu_1037_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal obj_ok_fu_950_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_1014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_2_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal subj_ok_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_1066_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_fu_1066_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln28_1_fu_1089_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_1100_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_1100_p11 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln29_1_fu_1123_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln31_3_fu_1134_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln32_1_fu_1144_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln33_1_fu_1154_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln32_1_fu_1149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_1_fu_1159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln31_4_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_1_fu_1139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_1_fu_1176_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln31_5_fu_1170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_fu_1181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_and_ln31_5_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_1_fu_1198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln98_1_fu_1215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal obj_ok_1_fu_1128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_18_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_3_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal subj_ok_1_fu_1094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_1_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln59_fu_1512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln56_fu_1516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rule_b_reg_attributes_7_fu_1529_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_7_fu_1529_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal sel_tmp7_fu_1521_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_4_fu_1549_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_4_fu_1549_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_5_fu_1569_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_5_fu_1569_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_6_fu_1589_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_attributes_6_fu_1589_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_7_fu_1609_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_7_fu_1609_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_4_fu_1629_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_4_fu_1629_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_5_fu_1649_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_5_fu_1649_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_6_fu_1669_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_objects_6_fu_1669_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_7_fu_1689_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_7_fu_1689_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_4_fu_1709_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_4_fu_1709_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_5_fu_1729_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_5_fu_1729_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_6_fu_1749_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_subjects_6_fu_1749_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_6_fu_1348_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_5_fu_1338_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_4_fu_1328_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_attributes_7_fu_1318_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_6_fu_1308_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_5_fu_1298_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_4_fu_1288_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_objects_7_fu_1278_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_5_fu_1268_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_4_fu_1258_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_7_fu_1248_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_a_reg_subjects_6_fu_1244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal rule_b_reg_required_provenance_val_fu_1853_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rule_b_reg_required_provenance_val_fu_1853_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal rule_b_reg_required_states_val9_fu_1873_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rule_b_reg_required_states_val9_fu_1873_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln58_1_fu_1368_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln58_s_fu_1358_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln50_fu_2047_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal prov_ok_fu_2065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_2_fu_2069_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal prov_ok_1_fu_2079_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_3_fu_2083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_fu_2074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_1_fu_2088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln51_4_fu_2093_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln50_1_fu_2099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_4_fu_2105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln50_fu_2053_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln51_5_fu_2111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal found_1_fu_2125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal found_1_fu_2125_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal found_1_fu_2125_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_888_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_888_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_888_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_888_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_922_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_922_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_922_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_922_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1066_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1066_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1066_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1066_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1100_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1100_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1100_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_1100_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_7_fu_1529_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_7_fu_1529_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_7_fu_1529_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_4_fu_1549_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_4_fu_1549_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_4_fu_1549_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_5_fu_1569_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_5_fu_1569_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_5_fu_1569_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_6_fu_1589_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_6_fu_1589_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_attributes_6_fu_1589_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_7_fu_1609_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_7_fu_1609_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_7_fu_1609_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_4_fu_1629_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_4_fu_1629_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_4_fu_1629_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_5_fu_1649_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_5_fu_1649_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_5_fu_1649_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_6_fu_1669_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_6_fu_1669_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_objects_6_fu_1669_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_7_fu_1689_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_7_fu_1689_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_7_fu_1689_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_4_fu_1709_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_4_fu_1709_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_4_fu_1709_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_5_fu_1729_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_5_fu_1729_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_5_fu_1729_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_6_fu_1749_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_6_fu_1749_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_subjects_6_fu_1749_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_provenance_val_fu_1853_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_provenance_val_fu_1853_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_provenance_val_fu_1853_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_states_val9_fu_1873_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_states_val9_fu_1873_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal rule_b_reg_required_states_val9_fu_1873_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal found_1_fu_2125_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal found_1_fu_2125_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal found_1_fu_2125_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hngac_authorize_sparsemux_9_2_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        din3 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component hngac_authorize_sparsemux_7_2_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        din2 : IN STD_LOGIC_VECTOR (63 downto 0);
        def : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component hngac_authorize_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hngac_authorize_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component hngac_authorize_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_64_1_1_U25 : component hngac_authorize_sparsemux_9_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "10",
        din2_WIDTH => 64,
        CASE3 => "11",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_a_reg_subjects_fu_228,
        din1 => rule_a_reg_subjects_1_fu_232,
        din2 => rule_a_reg_subjects_2_fu_236,
        din3 => rule_a_reg_subjects_3_fu_240,
        def => tmp_fu_888_p9,
        sel => trunc_ln3,
        dout => tmp_fu_888_p11);

    sparsemux_9_2_64_1_1_U26 : component hngac_authorize_sparsemux_9_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "10",
        din2_WIDTH => 64,
        CASE3 => "11",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_a_reg_objects_fu_244,
        din1 => rule_a_reg_objects_1_fu_248,
        din2 => rule_a_reg_objects_2_fu_252,
        din3 => rule_a_reg_objects_3_fu_256,
        def => tmp_1_fu_922_p9,
        sel => trunc_ln2,
        dout => tmp_1_fu_922_p11);

    sparsemux_9_2_64_1_1_U27 : component hngac_authorize_sparsemux_9_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "10",
        din2_WIDTH => 64,
        CASE3 => "11",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_subjects_fu_276,
        din1 => rule_b_reg_subjects_1_fu_280,
        din2 => rule_b_reg_subjects_2_fu_284,
        din3 => rule_b_reg_subjects_3_fu_288,
        def => tmp_2_fu_1066_p9,
        sel => trunc_ln3,
        dout => tmp_2_fu_1066_p11);

    sparsemux_9_2_64_1_1_U28 : component hngac_authorize_sparsemux_9_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "10",
        din2_WIDTH => 64,
        CASE3 => "11",
        din3_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_objects_fu_292,
        din1 => rule_b_reg_objects_1_fu_296,
        din2 => rule_b_reg_objects_2_fu_300,
        din3 => rule_b_reg_objects_3_fu_304,
        def => tmp_3_fu_1100_p9,
        sel => trunc_ln2,
        dout => tmp_3_fu_1100_p11);

    sparsemux_7_2_64_1_1_U29 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_attributes_7_fu_1529_p2,
        din1 => rule_b_reg_attributes_3_fu_320,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_attributes_7_fu_1529_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_attributes_7_fu_1529_p9);

    sparsemux_7_2_64_1_1_U30 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_attributes_4_fu_1549_p2,
        din1 => rule_b_reg_attributes_2_fu_316,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_attributes_4_fu_1549_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_attributes_4_fu_1549_p9);

    sparsemux_7_2_64_1_1_U31 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_attributes_5_fu_1569_p2,
        din1 => rule_b_reg_attributes_1_fu_312,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_attributes_5_fu_1569_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_attributes_5_fu_1569_p9);

    sparsemux_7_2_64_1_1_U32 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_attributes_6_fu_1589_p2,
        din1 => rule_b_reg_attributes_fu_308,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_attributes_6_fu_1589_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_attributes_6_fu_1589_p9);

    sparsemux_7_2_64_1_1_U33 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_objects_7_fu_1609_p2,
        din1 => rule_b_reg_objects_3_fu_304,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_objects_7_fu_1609_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_objects_7_fu_1609_p9);

    sparsemux_7_2_64_1_1_U34 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_objects_4_fu_1629_p2,
        din1 => rule_b_reg_objects_2_fu_300,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_objects_4_fu_1629_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_objects_4_fu_1629_p9);

    sparsemux_7_2_64_1_1_U35 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_objects_5_fu_1649_p2,
        din1 => rule_b_reg_objects_1_fu_296,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_objects_5_fu_1649_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_objects_5_fu_1649_p9);

    sparsemux_7_2_64_1_1_U36 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_objects_6_fu_1669_p2,
        din1 => rule_b_reg_objects_fu_292,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_objects_6_fu_1669_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_objects_6_fu_1669_p9);

    sparsemux_7_2_64_1_1_U37 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_subjects_7_fu_1689_p2,
        din1 => rule_b_reg_subjects_3_fu_288,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_subjects_7_fu_1689_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_subjects_7_fu_1689_p9);

    sparsemux_7_2_64_1_1_U38 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_subjects_4_fu_1709_p2,
        din1 => rule_b_reg_subjects_2_fu_284,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_subjects_4_fu_1709_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_subjects_4_fu_1709_p9);

    sparsemux_7_2_64_1_1_U39 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_subjects_5_fu_1729_p2,
        din1 => rule_b_reg_subjects_1_fu_280,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_subjects_5_fu_1729_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_subjects_5_fu_1729_p9);

    sparsemux_7_2_64_1_1_U40 : component hngac_authorize_sparsemux_7_2_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 64,
        CASE1 => "01",
        din1_WIDTH => 64,
        CASE2 => "00",
        din2_WIDTH => 64,
        def_WIDTH => 64,
        sel_WIDTH => 2,
        dout_WIDTH => 64)
    port map (
        din0 => rule_b_reg_subjects_6_fu_1749_p2,
        din1 => rule_b_reg_subjects_fu_276,
        din2 => ap_const_lv64_0,
        def => rule_b_reg_subjects_6_fu_1749_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_subjects_6_fu_1749_p9);

    sparsemux_7_2_32_1_1_U41 : component hngac_authorize_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => rule_b_reg_required_provenance_val_fu_1853_p2,
        din1 => required_assign_1_fu_224,
        din2 => ap_const_lv32_0,
        def => rule_b_reg_required_provenance_val_fu_1853_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_required_provenance_val_fu_1853_p9);

    sparsemux_7_2_32_1_1_U42 : component hngac_authorize_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => rule_b_reg_required_states_val9_fu_1873_p2,
        din1 => rule_b_reg_required_states_val10_fu_220,
        din2 => ap_const_lv32_0,
        def => rule_b_reg_required_states_val9_fu_1873_p7,
        sel => sel_tmp7_fu_1521_p3,
        dout => rule_b_reg_required_states_val9_fu_1873_p9);

    sparsemux_7_2_1_1_1_U43 : component hngac_authorize_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => found_1_fu_2125_p2,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_0,
        def => found_1_fu_2125_p7,
        sel => found_1_fu_2125_p8,
        dout => found_1_fu_2125_p9);

    flow_control_loop_pipe_sequential_init_U : component hngac_authorize_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    found_reg_578_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln46_reg_2416_pp0_iter1_reg = ap_const_lv1_0))) then 
                found_reg_578 <= found_1_fu_2125_p9;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                found_reg_578 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    p_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln46_fu_751_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    p_fu_208 <= add_ln46_1_fu_757_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_208 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    required_assign_1_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    required_assign_1_fu_224 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    required_assign_1_fu_224 <= rule_b_reg_required_provenance_val_fu_1853_p9;
                end if;
            end if; 
        end if;
    end process;

    required_assign_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    required_assign_fu_216 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    required_assign_fu_216 <= rule_a_reg_required_provenance_val7_fu_1893_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_attributes_1_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_attributes_1_fu_264 <= rule_a_reg_attributes_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_attributes_1_fu_264 <= rule_a_reg_attributes_10_fu_1783_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_attributes_2_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_attributes_2_fu_268 <= rule_a_reg_attributes_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_attributes_2_fu_268 <= rule_a_reg_attributes_9_fu_1776_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_attributes_3_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_attributes_3_fu_272 <= rule_a_reg_attributes_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_attributes_3_fu_272 <= rule_a_reg_attributes_8_fu_1769_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_attributes_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_attributes_fu_260 <= rule_a_reg_attributes_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_attributes_fu_260 <= rule_a_reg_attributes_11_fu_1790_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_objects_1_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_objects_1_fu_248 <= rule_a_reg_objects_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_objects_1_fu_248 <= rule_a_reg_objects_10_fu_1811_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_objects_2_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_objects_2_fu_252 <= rule_a_reg_objects_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_objects_2_fu_252 <= rule_a_reg_objects_9_fu_1804_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_objects_3_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_objects_3_fu_256 <= rule_a_reg_objects_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_objects_3_fu_256 <= rule_a_reg_objects_8_fu_1797_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_objects_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_objects_fu_244 <= rule_a_reg_objects_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_objects_fu_244 <= rule_a_reg_objects_11_fu_1818_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_required_states_val6_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_required_states_val6_fu_212 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_required_states_val6_fu_212 <= rule_a_reg_required_states_val5_fu_1900_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_subjects_1_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_subjects_1_fu_232 <= rule_a_reg_subjects_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_subjects_1_fu_232 <= rule_a_reg_subjects_10_fu_1839_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_subjects_2_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_subjects_2_fu_236 <= rule_a_reg_subjects_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_subjects_2_fu_236 <= rule_a_reg_subjects_9_fu_1832_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_subjects_3_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_subjects_3_fu_240 <= rule_a_reg_subjects_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_subjects_3_fu_240 <= rule_a_reg_subjects_8_fu_1825_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_a_reg_subjects_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_a_reg_subjects_fu_228 <= rule_a_reg_subjects_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_a_reg_subjects_fu_228 <= rule_a_reg_subjects_11_fu_1846_p3;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_attributes_1_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_attributes_1_fu_312 <= rule_b_reg_attributes_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_attributes_1_fu_312 <= rule_b_reg_attributes_5_fu_1569_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_attributes_2_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_attributes_2_fu_316 <= rule_b_reg_attributes_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_attributes_2_fu_316 <= rule_b_reg_attributes_4_fu_1549_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_attributes_3_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_attributes_3_fu_320 <= rule_b_reg_attributes_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_attributes_3_fu_320 <= rule_b_reg_attributes_7_fu_1529_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_attributes_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_attributes_fu_308 <= rule_b_reg_attributes_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_attributes_fu_308 <= rule_b_reg_attributes_6_fu_1589_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_objects_1_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_objects_1_fu_296 <= rule_b_reg_objects_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_objects_1_fu_296 <= rule_b_reg_objects_5_fu_1649_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_objects_2_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_objects_2_fu_300 <= rule_b_reg_objects_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_objects_2_fu_300 <= rule_b_reg_objects_4_fu_1629_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_objects_3_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_objects_3_fu_304 <= rule_b_reg_objects_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_objects_3_fu_304 <= rule_b_reg_objects_7_fu_1609_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_objects_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_objects_fu_292 <= rule_b_reg_objects_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_objects_fu_292 <= rule_b_reg_objects_6_fu_1669_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_required_states_val10_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_required_states_val10_fu_220 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_required_states_val10_fu_220 <= rule_b_reg_required_states_val9_fu_1873_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_subjects_1_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_subjects_1_fu_280 <= rule_b_reg_subjects_1_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_subjects_1_fu_280 <= rule_b_reg_subjects_5_fu_1729_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_subjects_2_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_subjects_2_fu_284 <= rule_b_reg_subjects_2_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_subjects_2_fu_284 <= rule_b_reg_subjects_4_fu_1709_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_subjects_3_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_subjects_3_fu_288 <= rule_b_reg_subjects_3_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_subjects_3_fu_288 <= rule_b_reg_subjects_7_fu_1689_p9;
                end if;
            end if; 
        end if;
    end process;

    rule_b_reg_subjects_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rule_b_reg_subjects_fu_276 <= rule_b_reg_subjects_reload;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln46_reg_2416 = ap_const_lv1_0))) then 
                    rule_b_reg_subjects_fu_276 <= rule_b_reg_subjects_6_fu_1749_p9;
                end if;
            end if; 
        end if;
    end process;

    stage1_valid_reg_591_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln46_reg_2416_pp0_iter1_reg = ap_const_lv1_0))) then 
                stage1_valid_reg_591 <= stage1_valid_1_reg_2420_pp0_iter1_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                stage1_valid_reg_591 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln46_reg_2416 <= icmp_ln46_fu_751_p2;
                icmp_ln46_reg_2416_pp0_iter1_reg <= icmp_ln46_reg_2416;
                icmp_ln59_reg_2446 <= icmp_ln59_fu_788_p2;
                icmp_ln95_1_reg_2481 <= icmp_ln95_1_fu_1209_p2;
                icmp_ln95_reg_2461 <= icmp_ln95_fu_1031_p2;
                icmp_ln98_1_reg_2486 <= icmp_ln98_1_fu_1220_p2;
                icmp_ln98_reg_2466 <= icmp_ln98_fu_1042_p2;
                stage1_valid_1_reg_2420_pp0_iter1_reg <= stage1_valid_1_reg_2420;
                state_ok_1_reg_2476 <= state_ok_1_fu_1203_p2;
                state_ok_reg_2456 <= state_ok_fu_1025_p2;
                xor_ln37_1_reg_2491 <= xor_ln37_1_fu_1238_p2;
                xor_ln37_reg_2471 <= xor_ln37_fu_1060_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                stage1_valid_1_reg_2420 <= stage1_valid_1_fu_763_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln46_1_fu_757_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_1) + unsigned(ap_const_lv9_1));
    and_ln28_1_fu_1089_p2 <= (tmp_2_fu_1066_p11 and subj_mask);
    and_ln28_fu_911_p2 <= (tmp_fu_888_p11 and subj_mask);
    and_ln29_1_fu_1123_p2 <= (tmp_3_fu_1100_p11 and obj_mask);
    and_ln29_fu_945_p2 <= (tmp_1_fu_922_p11 and obj_mask);
    and_ln31_1_fu_986_p2 <= (icmp_ln33_fu_981_p2 and icmp_ln32_fu_971_p2);
    and_ln31_2_fu_992_p2 <= (icmp_ln31_fu_961_p2 and and_ln31_1_fu_986_p2);
    and_ln31_3_fu_1134_p2 <= (trunc_ln5 and rule_b_reg_attributes_fu_308);
    and_ln31_4_fu_1164_p2 <= (icmp_ln33_1_fu_1159_p2 and icmp_ln32_1_fu_1149_p2);
    and_ln31_5_fu_1170_p2 <= (icmp_ln31_1_fu_1139_p2 and and_ln31_4_fu_1164_p2);
    and_ln31_fu_956_p2 <= (trunc_ln5 and rule_a_reg_attributes_fu_260);
    and_ln32_1_fu_1144_p2 <= (trunc_ln6 and rule_b_reg_attributes_1_fu_312);
    and_ln32_fu_966_p2 <= (trunc_ln6 and rule_a_reg_attributes_1_fu_264);
    and_ln33_1_fu_1154_p2 <= (trunc_ln8 and rule_b_reg_attributes_2_fu_316);
    and_ln33_fu_976_p2 <= (trunc_ln8 and rule_a_reg_attributes_2_fu_268);
    and_ln34_1_fu_1176_p2 <= (trunc_ln9 and rule_b_reg_attributes_3_fu_320);
    and_ln34_fu_998_p2 <= (trunc_ln9 and rule_a_reg_attributes_3_fu_272);
    and_ln35_1_fu_1198_p2 <= (trunc_ln7 and rule_b_reg_required_states_val10_fu_220);
    and_ln35_fu_1020_p2 <= (trunc_ln7 and rule_a_reg_required_states_val6_fu_212);
    and_ln51_1_fu_2088_p2 <= (state_ok_1_reg_2476 and and_ln51_3_fu_2083_p2);
    and_ln51_2_fu_2069_p2 <= (xor_ln37_reg_2471 and prov_ok_fu_2065_p2);
    and_ln51_3_fu_2083_p2 <= (xor_ln37_1_reg_2491 and prov_ok_1_fu_2079_p2);
    and_ln51_4_fu_2105_p2 <= (xor_ln50_1_fu_2099_p2 and or_ln51_4_fu_2093_p2);
    and_ln51_5_fu_2111_p2 <= (stage1_valid_reg_591 and and_ln51_4_fu_2105_p2);
    and_ln51_fu_2074_p2 <= (state_ok_reg_2456 and and_ln51_2_fu_2069_p2);
    and_ln59_fu_1512_p2 <= (stage1_valid_1_reg_2420 and icmp_ln59_reg_2446);
    and_ln98_1_fu_1215_p2 <= (source_assign and required_assign_1_fu_224);
    and_ln98_fu_1037_p2 <= (source_assign and required_assign_fu_216);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln46_fu_751_p2)
    begin
        if (((icmp_ln46_fu_751_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln46_reg_2416)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_reg_2416 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, p_fu_208)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_p_1 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_p_1 <= p_fu_208;
        end if; 
    end process;

    empty_18_fu_1192_p2 <= (not_and_ln31_5_fu_1186_p2 or icmp_ln34_1_fu_1181_p2);
    empty_fu_1014_p2 <= (not_and_ln31_2_fu_1008_p2 or icmp_ln34_fu_1003_p2);
    found_1_fu_2125_p2 <= (stage1_valid_reg_591 or found_reg_578);
    found_1_fu_2125_p7 <= "X";
    found_1_fu_2125_p8 <= (or_ln50_fu_2053_p2 & and_ln51_5_fu_2111_p2);
    found_out <= found_reg_578;

    found_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln46_reg_2416, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln46_reg_2416 = ap_const_lv1_1))) then 
            found_out_ap_vld <= ap_const_logic_1;
        else 
            found_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln31_1_fu_1139_p2 <= "1" when (and_ln31_3_fu_1134_p2 = trunc_ln5) else "0";
    icmp_ln31_fu_961_p2 <= "1" when (and_ln31_fu_956_p2 = trunc_ln5) else "0";
    icmp_ln32_1_fu_1149_p2 <= "1" when (and_ln32_1_fu_1144_p2 = trunc_ln6) else "0";
    icmp_ln32_fu_971_p2 <= "1" when (and_ln32_fu_966_p2 = trunc_ln6) else "0";
    icmp_ln33_1_fu_1159_p2 <= "1" when (and_ln33_1_fu_1154_p2 = trunc_ln8) else "0";
    icmp_ln33_fu_981_p2 <= "1" when (and_ln33_fu_976_p2 = trunc_ln8) else "0";
    icmp_ln34_1_fu_1181_p2 <= "0" when (and_ln34_1_fu_1176_p2 = trunc_ln9) else "1";
    icmp_ln34_fu_1003_p2 <= "0" when (and_ln34_fu_998_p2 = trunc_ln9) else "1";
    icmp_ln46_fu_751_p2 <= "1" when (ap_sig_allocacmp_p_1 = add_ln46) else "0";
    icmp_ln59_fu_788_p2 <= "1" when (unsigned(or_ln_fu_780_p3) < unsigned(bounded_rule_count)) else "0";
    icmp_ln95_1_fu_1209_p2 <= "1" when (required_assign_1_fu_224 = ap_const_lv32_0) else "0";
    icmp_ln95_fu_1031_p2 <= "1" when (required_assign_fu_216 = ap_const_lv32_0) else "0";
    icmp_ln98_1_fu_1220_p2 <= "0" when (and_ln98_1_fu_1215_p2 = ap_const_lv32_0) else "1";
    icmp_ln98_fu_1042_p2 <= "0" when (and_ln98_fu_1037_p2 = ap_const_lv32_0) else "1";
    not_and_ln31_2_fu_1008_p2 <= (ap_const_lv1_1 xor and_ln31_2_fu_992_p2);
    not_and_ln31_5_fu_1186_p2 <= (ap_const_lv1_1 xor and_ln31_5_fu_1170_p2);
    obj_ok_1_fu_1128_p2 <= "1" when (and_ln29_1_fu_1123_p2 = ap_const_lv64_0) else "0";
    obj_ok_fu_950_p2 <= "1" when (and_ln29_fu_945_p2 = ap_const_lv64_0) else "0";
    or_ln50_fu_2053_p2 <= (xor_ln50_fu_2047_p2 or found_reg_578);
    or_ln51_1_fu_1232_p2 <= (subj_ok_1_fu_1094_p2 or or_ln51_3_fu_1226_p2);
    or_ln51_2_fu_1048_p2 <= (obj_ok_fu_950_p2 or empty_fu_1014_p2);
    or_ln51_3_fu_1226_p2 <= (obj_ok_1_fu_1128_p2 or empty_18_fu_1192_p2);
    or_ln51_4_fu_2093_p2 <= (and_ln51_fu_2074_p2 or and_ln51_1_fu_2088_p2);
    or_ln51_fu_1054_p2 <= (subj_ok_fu_916_p2 or or_ln51_2_fu_1048_p2);
    or_ln_fu_780_p3 <= (ap_sig_allocacmp_p_1 & ap_const_lv1_1);
    policy_Addr_A <= policy_Addr_A_local;
    policy_Addr_A_local <= std_logic_vector(shift_left(unsigned(policy_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    policy_Addr_A_orig <= zext_ln60_fu_794_p1(32 - 1 downto 0);
    policy_Addr_B <= policy_Addr_B_local;
    policy_Addr_B_local <= std_logic_vector(shift_left(unsigned(policy_Addr_B_orig),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    policy_Addr_B_orig <= zext_ln58_fu_775_p1(32 - 1 downto 0);
    policy_Din_A <= ap_const_lv1024_lc_1;
    policy_Din_B <= ap_const_lv1024_lc_1;
    policy_EN_A <= policy_EN_A_local;

    policy_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            policy_EN_A_local <= ap_const_logic_1;
        else 
            policy_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    policy_EN_B <= policy_EN_B_local;

    policy_EN_B_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            policy_EN_B_local <= ap_const_logic_1;
        else 
            policy_EN_B_local <= ap_const_logic_0;
        end if; 
    end process;

    policy_WEN_A <= ap_const_lv128_lc_1;
    policy_WEN_B <= ap_const_lv128_lc_1;
    prov_ok_1_fu_2079_p2 <= (icmp_ln98_1_reg_2486 or icmp_ln95_1_reg_2481);
    prov_ok_fu_2065_p2 <= (icmp_ln98_reg_2466 or icmp_ln95_reg_2461);
    rule_a_reg_attributes_10_fu_1783_p3 <= 
        rule_a_reg_attributes_4_fu_1328_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_attributes_1_fu_264;
    rule_a_reg_attributes_11_fu_1790_p3 <= 
        rule_a_reg_attributes_7_fu_1318_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_attributes_fu_260;
    rule_a_reg_attributes_4_fu_1328_p4 <= policy_Dout_B(639 downto 576);
    rule_a_reg_attributes_5_fu_1338_p4 <= policy_Dout_B(703 downto 640);
    rule_a_reg_attributes_6_fu_1348_p4 <= policy_Dout_B(767 downto 704);
    rule_a_reg_attributes_7_fu_1318_p4 <= policy_Dout_B(575 downto 512);
    rule_a_reg_attributes_8_fu_1769_p3 <= 
        rule_a_reg_attributes_6_fu_1348_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_attributes_3_fu_272;
    rule_a_reg_attributes_9_fu_1776_p3 <= 
        rule_a_reg_attributes_5_fu_1338_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_attributes_2_fu_268;
    rule_a_reg_objects_10_fu_1811_p3 <= 
        rule_a_reg_objects_4_fu_1288_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_objects_1_fu_248;
    rule_a_reg_objects_11_fu_1818_p3 <= 
        rule_a_reg_objects_7_fu_1278_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_objects_fu_244;
    rule_a_reg_objects_4_fu_1288_p4 <= policy_Dout_B(383 downto 320);
    rule_a_reg_objects_5_fu_1298_p4 <= policy_Dout_B(447 downto 384);
    rule_a_reg_objects_6_fu_1308_p4 <= policy_Dout_B(511 downto 448);
    rule_a_reg_objects_7_fu_1278_p4 <= policy_Dout_B(319 downto 256);
    rule_a_reg_objects_8_fu_1797_p3 <= 
        rule_a_reg_objects_6_fu_1308_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_objects_3_fu_256;
    rule_a_reg_objects_9_fu_1804_p3 <= 
        rule_a_reg_objects_5_fu_1298_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_objects_2_fu_252;
    rule_a_reg_required_provenance_val7_fu_1893_p3 <= 
        trunc_ln58_1_fu_1368_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        required_assign_fu_216;
    rule_a_reg_required_states_val5_fu_1900_p3 <= 
        trunc_ln58_s_fu_1358_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_required_states_val6_fu_212;
    rule_a_reg_subjects_10_fu_1839_p3 <= 
        rule_a_reg_subjects_7_fu_1248_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_subjects_1_fu_232;
    rule_a_reg_subjects_11_fu_1846_p3 <= 
        rule_a_reg_subjects_6_fu_1244_p1 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_subjects_fu_228;
    rule_a_reg_subjects_4_fu_1258_p4 <= policy_Dout_B(191 downto 128);
    rule_a_reg_subjects_5_fu_1268_p4 <= policy_Dout_B(255 downto 192);
    rule_a_reg_subjects_6_fu_1244_p1 <= policy_Dout_B(64 - 1 downto 0);
    rule_a_reg_subjects_7_fu_1248_p4 <= policy_Dout_B(127 downto 64);
    rule_a_reg_subjects_8_fu_1825_p3 <= 
        rule_a_reg_subjects_5_fu_1268_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_subjects_3_fu_240;
    rule_a_reg_subjects_9_fu_1832_p3 <= 
        rule_a_reg_subjects_4_fu_1258_p4 when (stage1_valid_1_reg_2420(0) = '1') else 
        rule_a_reg_subjects_2_fu_236;
    rule_b_reg_attributes_4_fu_1549_p2 <= policy_Dout_A(703 downto 640);
    rule_b_reg_attributes_4_fu_1549_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_attributes_5_fu_1569_p2 <= policy_Dout_A(639 downto 576);
    rule_b_reg_attributes_5_fu_1569_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_attributes_6_fu_1589_p2 <= policy_Dout_A(575 downto 512);
    rule_b_reg_attributes_6_fu_1589_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_attributes_7_fu_1529_p2 <= policy_Dout_A(767 downto 704);
    rule_b_reg_attributes_7_fu_1529_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_objects_4_fu_1629_p2 <= policy_Dout_A(447 downto 384);
    rule_b_reg_objects_4_fu_1629_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_objects_5_fu_1649_p2 <= policy_Dout_A(383 downto 320);
    rule_b_reg_objects_5_fu_1649_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_objects_6_fu_1669_p2 <= policy_Dout_A(319 downto 256);
    rule_b_reg_objects_6_fu_1669_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_objects_7_fu_1609_p2 <= policy_Dout_A(511 downto 448);
    rule_b_reg_objects_7_fu_1609_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_required_provenance_val_fu_1853_p2 <= policy_Dout_A(831 downto 800);
    rule_b_reg_required_provenance_val_fu_1853_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_required_states_val9_fu_1873_p2 <= policy_Dout_A(799 downto 768);
    rule_b_reg_required_states_val9_fu_1873_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_subjects_4_fu_1709_p2 <= policy_Dout_A(191 downto 128);
    rule_b_reg_subjects_4_fu_1709_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_subjects_5_fu_1729_p2 <= policy_Dout_A(127 downto 64);
    rule_b_reg_subjects_5_fu_1729_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_subjects_6_fu_1749_p2 <= policy_Dout_A(64 - 1 downto 0);
    rule_b_reg_subjects_6_fu_1749_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    rule_b_reg_subjects_7_fu_1689_p2 <= policy_Dout_A(255 downto 192);
    rule_b_reg_subjects_7_fu_1689_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    sel_tmp7_fu_1521_p3 <= (and_ln59_fu_1512_p2 & xor_ln56_fu_1516_p2);
    shl_ln57_fu_769_p2 <= std_logic_vector(shift_left(unsigned(ap_sig_allocacmp_p_1),to_integer(unsigned('0' & ap_const_lv9_1(9-1 downto 0)))));
    stage1_valid_1_fu_763_p2 <= "1" when (unsigned(ap_sig_allocacmp_p_1) < unsigned(trunc_ln4)) else "0";
    state_ok_1_fu_1203_p2 <= "1" when (and_ln35_1_fu_1198_p2 = rule_b_reg_required_states_val10_fu_220) else "0";
    state_ok_fu_1025_p2 <= "1" when (and_ln35_fu_1020_p2 = rule_a_reg_required_states_val6_fu_212) else "0";
    subj_ok_1_fu_1094_p2 <= "1" when (and_ln28_1_fu_1089_p2 = ap_const_lv64_0) else "0";
    subj_ok_fu_916_p2 <= "1" when (and_ln28_fu_911_p2 = ap_const_lv64_0) else "0";
    tmp_1_fu_922_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_1066_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_3_fu_1100_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_888_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln58_1_fu_1368_p4 <= policy_Dout_B(831 downto 800);
    trunc_ln58_s_fu_1358_p4 <= policy_Dout_B(799 downto 768);
    xor_ln37_1_fu_1238_p2 <= (or_ln51_1_fu_1232_p2 xor ap_const_lv1_1);
    xor_ln37_fu_1060_p2 <= (or_ln51_fu_1054_p2 xor ap_const_lv1_1);
    xor_ln50_1_fu_2099_p2 <= (found_reg_578 xor ap_const_lv1_1);
    xor_ln50_fu_2047_p2 <= (stage1_valid_reg_591 xor ap_const_lv1_1);
    xor_ln56_fu_1516_p2 <= (stage1_valid_1_reg_2420 xor ap_const_lv1_1);
    zext_ln58_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln57_fu_769_p2),64));
    zext_ln60_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_780_p3),64));
end behav;
