-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hngac_authorize is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    policy_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    policy_EN_A : OUT STD_LOGIC;
    policy_WEN_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    policy_Din_A : OUT STD_LOGIC_VECTOR (1023 downto 0);
    policy_Dout_A : IN STD_LOGIC_VECTOR (1023 downto 0);
    policy_Clk_A : OUT STD_LOGIC;
    policy_Rst_A : OUT STD_LOGIC;
    policy_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    policy_EN_B : OUT STD_LOGIC;
    policy_WEN_B : OUT STD_LOGIC_VECTOR (127 downto 0);
    policy_Din_B : OUT STD_LOGIC_VECTOR (1023 downto 0);
    policy_Dout_B : IN STD_LOGIC_VECTOR (1023 downto 0);
    policy_Clk_B : OUT STD_LOGIC;
    policy_Rst_B : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of hngac_authorize is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hngac_authorize_hngac_authorize,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.965000,HLS_SYN_LAT=72,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2679,HLS_SYN_LUT=5104,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv16_200 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rule_count : STD_LOGIC_VECTOR (15 downto 0);
    signal request : STD_LOGIC_VECTOR (383 downto 0);
    signal icmp_ln14_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_1_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_1_reg_780 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln21_fu_377_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln21_reg_784 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1_reg_789 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln2_reg_794 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln3_reg_799 : STD_LOGIC_VECTOR (1 downto 0);
    signal bounded_rule_count_fu_417_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal bounded_rule_count_reg_804 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln5_reg_810 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln6_reg_815 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln7_reg_820 : STD_LOGIC_VECTOR (31 downto 0);
    signal source_assign_reg_825 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln8_reg_830 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln9_reg_835 : STD_LOGIC_VECTOR (63 downto 0);
    signal subj_mask_fu_488_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal subj_mask_reg_840 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal obj_mask_fu_497_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal obj_mask_reg_845 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln4_fu_604_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln4_reg_922 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln46_fu_615_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln46_reg_927 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hngac_authorize_Pipeline_1_fu_249_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out_ap_vld : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_idle : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_A : STD_LOGIC_VECTOR (1023 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B : STD_LOGIC;
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_B : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_B : STD_LOGIC_VECTOR (1023 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out_ap_vld : STD_LOGIC;
    signal ap_phi_mux_retval_0_phi_fu_242_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_reg_238 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg : STD_LOGIC := '0';
    signal grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_fu_345_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_361_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln19_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_341_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln22_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_fu_494_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln40_fu_583_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return : STD_LOGIC_VECTOR (0 downto 0);

    component hngac_authorize_hngac_authorize_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_a_reg_subjects_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_3_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_subjects_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_2_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_subjects_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_1_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_subjects_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_a_reg_objects_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_3_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_objects_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_2_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_objects_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_1_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_objects_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_a_reg_attributes_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_3_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_attributes_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_2_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_attributes_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_1_out_ap_vld : OUT STD_LOGIC;
        rule_a_reg_attributes_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_b_reg_subjects_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_3_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_subjects_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_2_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_subjects_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_1_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_subjects_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_b_reg_objects_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_3_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_objects_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_2_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_objects_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_1_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_objects_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_b_reg_attributes_3_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_3_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_attributes_2_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_2_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_attributes_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_1_out_ap_vld : OUT STD_LOGIC;
        rule_b_reg_attributes_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rule_b_reg_attributes_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_attributes_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_objects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_b_reg_subjects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_attributes_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_objects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_3_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_2_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_1_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        rule_a_reg_subjects_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        add_ln46 : IN STD_LOGIC_VECTOR (8 downto 0);
        trunc_ln3 : IN STD_LOGIC_VECTOR (1 downto 0);
        subj_mask : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln2 : IN STD_LOGIC_VECTOR (1 downto 0);
        obj_mask : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln5 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln6 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln8 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln9 : IN STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln7 : IN STD_LOGIC_VECTOR (31 downto 0);
        source_assign : IN STD_LOGIC_VECTOR (31 downto 0);
        trunc_ln4 : IN STD_LOGIC_VECTOR (8 downto 0);
        policy_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        policy_EN_A : OUT STD_LOGIC;
        policy_WEN_A : OUT STD_LOGIC_VECTOR (127 downto 0);
        policy_Din_A : OUT STD_LOGIC_VECTOR (1023 downto 0);
        policy_Dout_A : IN STD_LOGIC_VECTOR (1023 downto 0);
        policy_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        policy_EN_B : OUT STD_LOGIC;
        policy_WEN_B : OUT STD_LOGIC_VECTOR (127 downto 0);
        policy_Din_B : OUT STD_LOGIC_VECTOR (1023 downto 0);
        policy_Dout_B : IN STD_LOGIC_VECTOR (1023 downto 0);
        bounded_rule_count : IN STD_LOGIC_VECTOR (9 downto 0);
        found_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        found_out_ap_vld : OUT STD_LOGIC );
    end component;


    component hngac_authorize_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (0 downto 0);
        rule_count : OUT STD_LOGIC_VECTOR (15 downto 0);
        request : OUT STD_LOGIC_VECTOR (383 downto 0) );
    end component;



begin
    grp_hngac_authorize_Pipeline_1_fu_249 : component hngac_authorize_hngac_authorize_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_1_fu_249_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_1_fu_249_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_1_fu_249_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_1_fu_249_ap_ready,
        rule_a_reg_subjects_3_out => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out,
        rule_a_reg_subjects_3_out_ap_vld => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out_ap_vld,
        rule_a_reg_subjects_2_out => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out,
        rule_a_reg_subjects_2_out_ap_vld => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out_ap_vld,
        rule_a_reg_subjects_1_out => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out,
        rule_a_reg_subjects_1_out_ap_vld => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out_ap_vld,
        rule_a_reg_subjects_out => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out,
        rule_a_reg_subjects_out_ap_vld => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out_ap_vld);

    grp_hngac_authorize_Pipeline_2_fu_257 : component hngac_authorize_hngac_authorize_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_2_fu_257_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_2_fu_257_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_2_fu_257_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_2_fu_257_ap_ready,
        rule_a_reg_objects_3_out => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out,
        rule_a_reg_objects_3_out_ap_vld => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out_ap_vld,
        rule_a_reg_objects_2_out => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out,
        rule_a_reg_objects_2_out_ap_vld => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out_ap_vld,
        rule_a_reg_objects_1_out => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out,
        rule_a_reg_objects_1_out_ap_vld => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out_ap_vld,
        rule_a_reg_objects_out => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out,
        rule_a_reg_objects_out_ap_vld => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out_ap_vld);

    grp_hngac_authorize_Pipeline_3_fu_265 : component hngac_authorize_hngac_authorize_Pipeline_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_3_fu_265_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_3_fu_265_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_3_fu_265_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_3_fu_265_ap_ready,
        rule_a_reg_attributes_3_out => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out,
        rule_a_reg_attributes_3_out_ap_vld => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out_ap_vld,
        rule_a_reg_attributes_2_out => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out,
        rule_a_reg_attributes_2_out_ap_vld => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out_ap_vld,
        rule_a_reg_attributes_1_out => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out,
        rule_a_reg_attributes_1_out_ap_vld => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out_ap_vld,
        rule_a_reg_attributes_out => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out,
        rule_a_reg_attributes_out_ap_vld => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out_ap_vld);

    grp_hngac_authorize_Pipeline_4_fu_273 : component hngac_authorize_hngac_authorize_Pipeline_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_4_fu_273_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_4_fu_273_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_4_fu_273_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_4_fu_273_ap_ready,
        rule_b_reg_subjects_3_out => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out,
        rule_b_reg_subjects_3_out_ap_vld => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out_ap_vld,
        rule_b_reg_subjects_2_out => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out,
        rule_b_reg_subjects_2_out_ap_vld => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out_ap_vld,
        rule_b_reg_subjects_1_out => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out,
        rule_b_reg_subjects_1_out_ap_vld => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out_ap_vld,
        rule_b_reg_subjects_out => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out,
        rule_b_reg_subjects_out_ap_vld => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out_ap_vld);

    grp_hngac_authorize_Pipeline_5_fu_281 : component hngac_authorize_hngac_authorize_Pipeline_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_5_fu_281_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_5_fu_281_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_5_fu_281_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_5_fu_281_ap_ready,
        rule_b_reg_objects_3_out => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out,
        rule_b_reg_objects_3_out_ap_vld => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out_ap_vld,
        rule_b_reg_objects_2_out => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out,
        rule_b_reg_objects_2_out_ap_vld => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out_ap_vld,
        rule_b_reg_objects_1_out => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out,
        rule_b_reg_objects_1_out_ap_vld => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out_ap_vld,
        rule_b_reg_objects_out => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out,
        rule_b_reg_objects_out_ap_vld => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out_ap_vld);

    grp_hngac_authorize_Pipeline_6_fu_289 : component hngac_authorize_hngac_authorize_Pipeline_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_6_fu_289_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_6_fu_289_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_6_fu_289_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_6_fu_289_ap_ready,
        rule_b_reg_attributes_3_out => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out,
        rule_b_reg_attributes_3_out_ap_vld => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out_ap_vld,
        rule_b_reg_attributes_2_out => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out,
        rule_b_reg_attributes_2_out_ap_vld => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out_ap_vld,
        rule_b_reg_attributes_1_out => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out,
        rule_b_reg_attributes_1_out_ap_vld => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out_ap_vld,
        rule_b_reg_attributes_out => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out,
        rule_b_reg_attributes_out_ap_vld => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out_ap_vld);

    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297 : component hngac_authorize_hngac_authorize_Pipeline_VITIS_LOOP_46_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start,
        ap_done => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done,
        ap_idle => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_idle,
        ap_ready => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready,
        rule_b_reg_attributes_3_reload => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_3_out,
        rule_b_reg_attributes_2_reload => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_2_out,
        rule_b_reg_attributes_1_reload => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_1_out,
        rule_b_reg_attributes_reload => grp_hngac_authorize_Pipeline_6_fu_289_rule_b_reg_attributes_out,
        rule_b_reg_objects_3_reload => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_3_out,
        rule_b_reg_objects_2_reload => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_2_out,
        rule_b_reg_objects_1_reload => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_1_out,
        rule_b_reg_objects_reload => grp_hngac_authorize_Pipeline_5_fu_281_rule_b_reg_objects_out,
        rule_b_reg_subjects_3_reload => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_3_out,
        rule_b_reg_subjects_2_reload => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_2_out,
        rule_b_reg_subjects_1_reload => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_1_out,
        rule_b_reg_subjects_reload => grp_hngac_authorize_Pipeline_4_fu_273_rule_b_reg_subjects_out,
        rule_a_reg_attributes_3_reload => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_3_out,
        rule_a_reg_attributes_2_reload => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_2_out,
        rule_a_reg_attributes_1_reload => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_1_out,
        rule_a_reg_attributes_reload => grp_hngac_authorize_Pipeline_3_fu_265_rule_a_reg_attributes_out,
        rule_a_reg_objects_3_reload => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_3_out,
        rule_a_reg_objects_2_reload => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_2_out,
        rule_a_reg_objects_1_reload => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_1_out,
        rule_a_reg_objects_reload => grp_hngac_authorize_Pipeline_2_fu_257_rule_a_reg_objects_out,
        rule_a_reg_subjects_3_reload => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_3_out,
        rule_a_reg_subjects_2_reload => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_2_out,
        rule_a_reg_subjects_1_reload => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_1_out,
        rule_a_reg_subjects_reload => grp_hngac_authorize_Pipeline_1_fu_249_rule_a_reg_subjects_out,
        add_ln46 => add_ln46_reg_927,
        trunc_ln3 => trunc_ln3_reg_799,
        subj_mask => subj_mask_reg_840,
        trunc_ln2 => trunc_ln2_reg_794,
        obj_mask => obj_mask_reg_845,
        trunc_ln5 => trunc_ln5_reg_810,
        trunc_ln6 => trunc_ln6_reg_815,
        trunc_ln8 => trunc_ln8_reg_830,
        trunc_ln9 => trunc_ln9_reg_835,
        trunc_ln7 => trunc_ln7_reg_820,
        source_assign => source_assign_reg_825,
        trunc_ln4 => trunc_ln4_reg_922,
        policy_Addr_A => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A,
        policy_EN_A => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A,
        policy_WEN_A => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_A,
        policy_Din_A => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_A,
        policy_Dout_A => policy_Dout_A,
        policy_Addr_B => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B,
        policy_EN_B => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B,
        policy_WEN_B => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_WEN_B,
        policy_Din_B => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Din_B,
        policy_Dout_B => policy_Dout_B,
        bounded_rule_count => bounded_rule_count_reg_804,
        found_out => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out,
        found_out_ap_vld => grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out_ap_vld);

    control_s_axi_U : component hngac_authorize_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => ap_phi_mux_retval_0_phi_fu_242_p4,
        rule_count => rule_count,
        request => request);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_1_fu_249_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_2_fu_257_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_3_fu_265_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_4_fu_273_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_5_fu_281_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_6_fu_289_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_ready = ap_const_logic_1)) then 
                    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    retval_0_reg_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln14_1_reg_780 = ap_const_lv1_1) and (icmp_ln14_reg_776 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                retval_0_reg_238 <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and ((icmp_ln14_1_fu_371_p2 = ap_const_lv1_0) or (icmp_ln14_fu_355_p2 = ap_const_lv1_0)))) then 
                retval_0_reg_238 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln46_reg_927 <= add_ln46_fu_615_p2;
                trunc_ln4_reg_922 <= add_ln40_fu_583_p2(9 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bounded_rule_count_reg_804 <= bounded_rule_count_fu_417_p3;
                icmp_ln14_1_reg_780 <= icmp_ln14_1_fu_371_p2;
                icmp_ln14_reg_776 <= icmp_ln14_fu_355_p2;
                source_assign_reg_825 <= request(383 downto 352);
                trunc_ln1_reg_789 <= request(21 downto 16);
                trunc_ln21_reg_784 <= trunc_ln21_fu_377_p1;
                trunc_ln2_reg_794 <= request(23 downto 22);
                trunc_ln3_reg_799 <= request(7 downto 6);
                trunc_ln5_reg_810 <= request(127 downto 64);
                trunc_ln6_reg_815 <= request(191 downto 128);
                trunc_ln7_reg_820 <= request(351 downto 320);
                trunc_ln8_reg_830 <= request(255 downto 192);
                trunc_ln9_reg_835 <= request(319 downto 256);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                obj_mask_reg_845 <= obj_mask_fu_497_p2;
                subj_mask_reg_840 <= subj_mask_fu_488_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln14_fu_355_p2, icmp_ln14_1_fu_371_p2, ap_CS_fsm_state2, grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done, ap_CS_fsm_state4, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and ((icmp_ln14_1_fu_371_p2 = ap_const_lv1_0) or (icmp_ln14_fu_355_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((icmp_ln14_1_fu_371_p2 = ap_const_lv1_1) and (icmp_ln14_fu_355_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln40_fu_583_p2 <= std_logic_vector(unsigned(bounded_rule_count_reg_804) + unsigned(ap_const_lv10_1));
    add_ln46_fu_615_p2 <= std_logic_vector(unsigned(trunc_ln4_fu_604_p4) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done)
    begin
        if ((grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_hngac_authorize_Pipeline_1_fu_249_ap_done, grp_hngac_authorize_Pipeline_2_fu_257_ap_done, grp_hngac_authorize_Pipeline_3_fu_265_ap_done, grp_hngac_authorize_Pipeline_4_fu_273_ap_done, grp_hngac_authorize_Pipeline_5_fu_281_ap_done, grp_hngac_authorize_Pipeline_6_fu_289_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_hngac_authorize_Pipeline_1_fu_249_ap_done = ap_const_logic_0) or (grp_hngac_authorize_Pipeline_6_fu_289_ap_done = ap_const_logic_0) or (grp_hngac_authorize_Pipeline_5_fu_281_ap_done = ap_const_logic_0) or (grp_hngac_authorize_Pipeline_4_fu_273_ap_done = ap_const_logic_0) or (grp_hngac_authorize_Pipeline_3_fu_265_ap_done = ap_const_logic_0) or (grp_hngac_authorize_Pipeline_2_fu_257_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_242_p4_assign_proc : process(icmp_ln14_reg_776, icmp_ln14_1_reg_780, grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out, retval_0_reg_238, ap_CS_fsm_state5)
    begin
        if (((icmp_ln14_1_reg_780 = ap_const_lv1_1) and (icmp_ln14_reg_776 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_phi_mux_retval_0_phi_fu_242_p4 <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_found_out;
        else 
            ap_phi_mux_retval_0_phi_fu_242_p4 <= retval_0_reg_238;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bounded_rule_count_fu_417_p3 <= 
        ap_const_lv10_200 when (icmp_ln19_fu_411_p2(0) = '1') else 
        empty_fu_341_p1;
    empty_fu_341_p1 <= rule_count(10 - 1 downto 0);
    grp_hngac_authorize_Pipeline_1_fu_249_ap_start <= grp_hngac_authorize_Pipeline_1_fu_249_ap_start_reg;
    grp_hngac_authorize_Pipeline_2_fu_257_ap_start <= grp_hngac_authorize_Pipeline_2_fu_257_ap_start_reg;
    grp_hngac_authorize_Pipeline_3_fu_265_ap_start <= grp_hngac_authorize_Pipeline_3_fu_265_ap_start_reg;
    grp_hngac_authorize_Pipeline_4_fu_273_ap_start <= grp_hngac_authorize_Pipeline_4_fu_273_ap_start_reg;
    grp_hngac_authorize_Pipeline_5_fu_281_ap_start <= grp_hngac_authorize_Pipeline_5_fu_281_ap_start_reg;
    grp_hngac_authorize_Pipeline_6_fu_289_ap_start <= grp_hngac_authorize_Pipeline_6_fu_289_ap_start_reg;
    grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_ap_start_reg;
    icmp_ln14_1_fu_371_p2 <= "1" when (tmp_1_fu_361_p4 = ap_const_lv8_0) else "0";
    icmp_ln14_fu_355_p2 <= "1" when (tmp_fu_345_p4 = ap_const_lv8_0) else "0";
    icmp_ln19_fu_411_p2 <= "1" when (unsigned(rule_count) > unsigned(ap_const_lv16_200)) else "0";
    obj_mask_fu_497_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_1),to_integer(unsigned('0' & zext_ln24_fu_494_p1(31-1 downto 0)))));
    policy_Addr_A <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_A;
    policy_Addr_B <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_Addr_B;
    policy_Clk_A <= ap_clk;
    policy_Clk_B <= ap_clk;
    policy_Din_A <= ap_const_lv1024_lc_1;
    policy_Din_B <= ap_const_lv1024_lc_1;
    policy_EN_A <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_A;
    policy_EN_B <= grp_hngac_authorize_Pipeline_VITIS_LOOP_46_1_fu_297_policy_EN_B;
    policy_Rst_A <= ap_rst_n_inv;
    policy_Rst_B <= ap_rst_n_inv;
    policy_WEN_A <= ap_const_lv128_lc_1;
    policy_WEN_B <= ap_const_lv128_lc_1;
    subj_mask_fu_488_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_1),to_integer(unsigned('0' & zext_ln22_fu_485_p1(31-1 downto 0)))));
    tmp_1_fu_361_p4 <= request(31 downto 24);
    tmp_fu_345_p4 <= request(15 downto 8);
    trunc_ln21_fu_377_p1 <= request(6 - 1 downto 0);
    trunc_ln4_fu_604_p4 <= add_ln40_fu_583_p2(9 downto 1);
    zext_ln22_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln21_reg_784),64));
    zext_ln24_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_reg_789),64));
end behav;
